#+setupfile: ./site.template
#+title: My Emacs configuration
#+date: <2020-10-31>
#+author: MinasMazar
#+email: minasmazar@gmail.com
#+property: header-args :comments yes

* Introduction
** Purposes
This is intended to be a really basic Emacs configuration. The main
features of this configuration are:

** KISS

Do not include all the super fancy featured packages for IDE or
OS-like extension of Emacs, but keep it simple, stupid and thin as
possible. It should work as a vanilla Emacs distribution, so trying
not to remap main keybindings, but adding a little set of important
keychords. This means no Evil mode, but God mode ([[http://tobytripp.github.io/emacs.d/god.html][here's a god article]]). I somethime miss the mighty [[https://www.vim.org/][vim]] edit mode, so feel free to activate [[https://github.com/emacs-evil/evil#start-of-content][evil-mode]].

** TODO Literate configuration

Basically, what you're reading now is the Emacs configuration: it is
an [[org-mode]] file which will be tangled via [[https://orgmode.org/features.html#babel][Org abel]]
(~org-babel-load-file~). You only have to copy/paste [[Init.el][init.el]].

... also take a look to ~#+PROPERTY: header-args :comments yes~ in the headers of this file!

** Out-of-the-box

It should be downloaded with CLI tools (like wget, curl), and the only additional operation required in order to let it work is the
extraction of the literate part into a dedicated `init.el`. This also
means, in some way, that it will be lightweight as possible. If you
want to add a particular set of configuration and packages, in order
to transform your Emacs into a wonderful IDE on just the unbeatable OS you've ever seen, you can [[Conventions][uncomment]] some blocks you will find along the way.

*** Init.el

In order to load this literate configuration file, your ~init.el~ should be something like the next code block. The code is can be [[https://orgmode.org/manual/Exporting-Code-Blocks.html][exported]] into the standard [[file:~/.emacs.d/init.el][init.el]] by simply evaluating the code itself with ~(org-ctrl-c-ctrl-c)~ or by pressing.. - guess what? ;)

#+begin_src emacs-lisp :tangle no :exports ~/.emacs.d/init.el :output 
(require 'package)

(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)

; For important compatibility libraries like cl-lib
(when (< emacs-major-version 24)
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))

(package-initialize)
(require 'use-package)
(use-package org
  :config
  (org-babel-load-file "~/.emacs.d/emacs.org"))
#+end_src

** Versionable

This file is intended to be in the root of a ~dotfiles~ like repo. For this reason some files are [[file:.gitignore][ignored]].

** Bloggable

It should contain all the informations, snippets and out-of-the-box
  shell code blocks in order to have an usable, self-documented,
  Emacs-centric blog. ;) We will take advantage of the [[https://orgmode.org/manual/Publishing.html][publishing
  feature]] of [[org-mode][org-mode]].

** Conventions

Somewhere in this configuration file you can find "uncomment the code
block". This usually means to remove =COMMENT= on heading, turn an *ORG* code block from [[https://orgmode.org/manual/Literal-Examples.html#Literal-Examples][~+begin_example~]] to [[https://orgmode.org/manual/Working-with-Source-Code.html#Working-with-Source-Code][~+begin_src~]], or to remove the ~:tangle no~ attribute.

Maybe is not a best practice for security reasons, but somewhere in
this document you can find [[https://orgmode.org/guide/Hyperlinks.html][org-links]] to elisp code which will run
elisp code on the fly, in order to quickly jump somewhere or make
something happens in your emacs (very useful for demontration
purposes), but *is very risky*.  *Ensure
~org-link-elisp-confirm-function~ is nil*; this way you will be asked
for confirmation and here you will see the command displayed in the
minibuffer.

*Anyway I can’t accept any responsibility or liability for
damages arising from evaluating untrusted lisp code on your machine.*

* Main configurations

These are some really basic customizations.

#+begin_src emacs-lisp
  (setq ring-bell-function 'ignore)
  (setq make-backup-files nil)
  (setq use-package-always-ensure t)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

** exec-path and PATH env
   
Append ~usr/local/bin~ to the ~PATH~

#+begin_src emacs-lisp
(push "/usr/local/bin" exec-path)
(push "~/.asdf/shims" exec-path)
(setenv "PATH" (string-join exec-path ":"))
#+end_src

** Additional (disabled) configuration

This is an example of other common variables you could wish having in place.

#+begin_example emacs-lisp
(custom-set-variables
  '(tab-always-indent 'complete)
  '(web-mode-code-indent-offset 2)
  '(web-mode-css-indent-offset 2)
  '(web-mode-markup-indent-offset 2))
#+end_example

** Buffer predicates

#+begin_src emacs-lisp
(defun no-helm-buffer-predicate (buffer)
  (if (string-match "helm" (buffer-name buffer))
      nil
    t))

(setq buffer-predicate 'no-helm-buffer-predicate)
#+end_src

** Main packages
*** COMMENT Projectile

#+begin_src emacs-lisp
  (use-package projectile
    :bind
    ("C-x p f" . projectile-find-file)
    ("C-x p b" . projectile-switch-to-buffer)
    ("C-x p s" . projectile-ripgrep)
    ("s-P" . projectile-find-file)
    ("s-{" . projectile-previous-project-buffer)
    ("s-}" . projectile-next-project-buffer))
#+end_src

** Eshell
   #+begin_src emacs-lisp
     (use-package eshell
       :custom
       (eshell-scroll-to-bottom-on-input 'all)
       (eshell-destroy-buffer-when-process-dies t)
       (eshell-env-path (getenv "PATH")))
   #+end_src

   Eshell aliases goes under ~~/.emacs.d/eshell/aliases~ as default. You can customize it with sometihg like that:

   #+begin_example emacs-lisp
   alias ff "find-file $*"
   alias rr "ripgrep-regexp . $1"
   #+end_example
** Shell commands

   Has mentioned [[https://emacs.stackexchange.com/questions/10570/executing-commands-through-shell-command-what-is-the-path-used][in this stackexchange thread]]..

#+begin_quote
when running M-x shell but not when running M-! / (shell-command), as there is no prompt. You can adjust the option flags that are sent to (shell-command) by adjusting shell-command-switch to instruct it to act interactively and load your shell dotfile with:
#+end_quote

#+begin_src emacs-lisp
(setq shell-command-switch "-ic")
#+end_src

** Exwm
   Emacs window manager sample configuration to put somewhere into your ~init.el~. 
   #+begin_example emacs-lisp
     (use-package exwm
       :config
       (menu-bar-mode -1)
       (tool-bar-mode -1)
       (scroll-bar-mode -1)
       ;; Also shrink fringes to 1 pixel.
       (fringe-mode 1)
       ;; Turn on `display-time-mode' if you don't use an external bar.
       (display-time-default-load-average nil)
       (display-time-mode t)
       (server-start)
       ;; Set the initial number of workspaces (they can also be created later).
       (setq exwm-workspace-number 4)
       ;; Fix problems with Ido (if you use it).
       ;;(require 'exwm-config)
       ;;(exwm-config-ido)
       )
   #+end_example

This is an example configuration to add into you ~~/.xinitrc~

#+begin_example
# You may need to comment out the next line to disable access control.
#xhost +SI:localuser:$USER

# Set themes, etc.
gnome-settings-daemon &

# Set fallback cursor.
xsetroot -cursor_name left_ptr

# Set keyboard repeat rate.
xset r rate 200 60

# If Emacs is started in server mode, `emacsclient` is a convenient way to
# edit files in place (used by e.g. `git commit`).
export VISUAL=emacsclient
export EDITOR="$VISUAL"

# Finally launch emacs.
exec dbus-launch --exit-with-session emacs
#+end_example
* Keybindings

These are my preferred keybindings

#+begin_src emacs-lisp
    (global-set-key (kbd "C-x C-F") 'find-file-at-point)
    (global-set-key (kbd "C-x p p") 'project-switch-open-project)
    (global-set-key (kbd "C-x p f") 'project-find-file)
    (global-set-key (kbd "C-x p b") 'project-switch-to-buffer)
    (global-set-key (kbd "C-x p k") 'project-kill-buffers)

    (defcustom mm/meta-prefix "C-." "mm/meta prefix")
    (global-set-key (kbd mm/meta-prefix) nil)
    (defun mm/meta-set-key (keystroke)
      "Set keystroke mm prefixed"
      (kbd (concat mm/meta-prefix " " keystroke)))

    (global-set-key (mm/meta-set-key "b") 'ibuffer)
    (global-set-key (mm/meta-set-key "h") '(lambda () (interactive)
                                             (find-file "~/.emacs.d/emacs.org")))
    (global-set-key (mm/meta-set-key "i m") 'imenu)
    (global-set-key (mm/meta-set-key "i b") 'ibuffer)
    (global-set-key (mm/meta-set-key "o a") 'org-agenda)
    (global-set-key (mm/meta-set-key "o c") 'org-capture)
    (global-set-key (mm/meta-set-key "e s") 'sh-send-line-or-region-and-step)
    (global-set-key (mm/meta-set-key "e e") 'eshell)
    (global-set-key (mm/meta-set-key "w") 'eww)
#+end_src

** Meta-key
Wants to take advantage of the meta key (i.e. ~CMD~ on MacOS, or
~Win~ on Windows) to set some useful shortcuts, [[KISS][trying to preserve the vanilla emacs muscle memory]]. So ~s-0~ for ~C-x 0~, ~s-3~ for ~C-x 3~ and so on..

#+begin_src emacs-lisp
  (global-set-key (kbd "s-c") 'kill-ring-save)
  (global-set-key (kbd "s-1") 'delete-other-windows)
  (global-set-key (kbd "s-3") 'split-window-horizontally)
  (global-set-key (kbd "s-2") 'split-window-vertically)
  (global-set-key (kbd "s-0") 'delete-window)
  (global-set-key (kbd "s-w") 'other-window)
  (global-set-key (kbd "s-W") '(lambda () (interactive)
                                 (other-window 1) (maximize-window)))
  (global-set-key (kbd "s-r") 'repeat)
  (global-set-key (kbd "s-K") 'switch-to-buffer)
  (global-set-key (kbd "s-p") 'project-switch-to-buffer)
  (global-set-key (kbd "s-P") 'project-find-file)
  (global-set-key (kbd "s-t") 'eshell)
  (global-set-key (kbd "s-[") 'previous-buffer)
  (global-set-key (kbd "s-]") 'next-buffer)
  (global-set-key (kbd "s--") 'bookmark-bmenu-list)
  (global-set-key (kbd "s-_") 'bookmark-set)
  (global-set-key (kbd "s-\\") 'other-frame)
  (global-set-key (kbd "s-N") 'dired-jump)
  (global-set-key (kbd "s-DEL") 'zap-up-to-char)
  (global-set-key (kbd "s-=") 'balance-windows)
  (global-set-key (kbd "s-)") 'kill-this-buffer)
#+end_src

Override ~isearch-mode-map~

#+begin_src emacs-lisp
  (define-key isearch-mode-map (kbd "C-p") 'isearch-repeat-backward)
  (define-key isearch-mode-map (kbd "C-n") 'isearch-repeat-forward)
  (define-key isearch-mode-map (kbd "<tab>") 'isearch-repeat-backward)
  (define-key isearch-mode-map (kbd "<S-tab>") 'isearch-repeat-forward)
#+end_src

Add shortcut in translation map which basically are fast access to ~C-x~ and ~C-c~.

#+begin_src emacs-lisp
  (define-key key-translation-map (kbd "s-k") (kbd "M-x"))
  (define-key key-translation-map (kbd "s-m") (kbd "C-x"))
  (define-key key-translation-map (kbd "s-M") (kbd "C-c"))
  (define-key key-translation-map (kbd "s-o") (kbd mm/meta-prefix))
#+end_src

* No meta (alt)?

   For some reason you can't use the ~alt~ key on your keyboard? (It happens to me with Iterm + ssh + emacsclient session) and for some reason you don't want to solve this issue configuring Iterm or else? In this case you use this workaround, remapping some core keybinding like ~C-k~ and ~C-l~.

#+begin_example emacs-lisp
  (global-set-key (kbd "C-k") 'execute-extended-command)
  (global-set-key (kbd "C-K") 'kill-visual-line)
  (global-set-key (kbd "C-l") 'god-local-mode)
  (global-set-key (kbd "C-L") 'recenter-top-bottom)
#+end_example
** Editing

#+begin_src emacs-lisp
  (global-set-key (kbd "C-; C-k") 'zap-up-to-char)
  (global-set-key (kbd "C-; C-;") 'dabbrev-expand)
#+end_src

** Autocompletion
*** Company

 A basic auto-completion package.

 #+begin_src emacs-lisp
 (use-package company
   :config
   (global-company-mode))
 #+end_src

** Highlight and markers

#+begin_src emacs-lisp
  (show-paren-mode t)
#+end_src

** Parenthesis

#+begin_src emacs-lisp
(use-package rainbow-mode)
#+end_src
** Expand region
#+begin_src emacs-lisp
  (use-package expand-region
    :bind
    ("s-l" . er/expand-region))
#+end_src

Used in tandem with

#+begin_src emacs-lisp
(pending-delete-mode t)
#+end_src
** Navigation
*** Jumping around
#+begin_src emacs-lisp
  (use-package ace-jump-mode
    :config
    (global-set-key (kbd "s-j") 'ace-jump-word-mode))
#+end_src
* Interactive

Here we define main packages and customizations concerning the interaction of the user with Emacs, basically the way inputs are prompted and selected. Here we offers also links for unused setup, but is here if you just want to experiment. Ido is the buil-in method, Ivy and Helm are valid alternatives.

** Completion styles
   #+begin_src emacs-lisp
(setq completion-styles '(substring initials flex partial-completion orderless))
(setq completion-category-overrides
            '((buffer (styles . (substring)))
              (file (styles . (initials orderless)))
              (project-file (styles . (initials orderless)))))
     ;; ;; (setq completion-flex-nospace t)
     ;; ;; (setq read-buffer-completion-ignore-case t)
     ;; (setq read-file-name-completion-ignore-case t)
     ;; (setq completion-show-help t)
     ;; (setq completion-auto-help t)
#+end_src
** Minibuffer
   #+begin_src emacs-lisp
     (define-key minibuffer-local-completion-map (kbd "<C-return>") 'minibuffer-force-complete-and-exit)
     (define-key minibuffer-local-completion-map (kbd "C-j") 'minibuffer-force-complete-and-exit)
     ;(define-key minibuffer-local-completion-map (kbd "<tab>") 'minibuffer-force-complete)
     (define-key minibuffer-local-completion-map (kbd "C-c") 'switch-to-completions)
     (define-key minibuffer-local-completion-map (kbd "C-o") 'switch-to-completions)
     #+end_src

** Icomplete
#+begin_src emacs-lisp
  (use-package icomplete
    :config
    (icomplete-mode nil)
    :bind
    (:map minibuffer-local-completion-map
          ("C-p" . icomplete-backward-completions)
          ("C-N" . icomplete-forward-completions)
          ("C-j" . icomplete-force-complete-and-exit)
          ("<C-return>" . icomplete-force-complete-and-exit)))
#+end_src

*** Vertical mode (should be built-in in Emacs >= 28)

#+begin_src emacs-lisp
  (use-package icomplete-vertical
    :config
    (icomplete-vertical-mode 1))
#+end_src

** Save history
   #+begin_src emacs-lisp
     (use-package savehist
       :init
       (savehist-mode))
   #+end_src
** Embark
   #+begin_src emacs-lisp
     (use-package embark
       :bind*
       ("C-," . embark-act))
   #+end_src
** Marginalia
   #+begin_src emacs-lisp
     (use-package marginalia
       :init
       (marginalia-mode 1))
   #+end_src
** Which key

#+begin_src emacs-lisp
(use-package which-key :config (which-key-mode t))
#+end_src

** God mode

#+begin_quote
NOTE: Emacs 25.1 is required for this package to work well.


This is a global minor mode for entering Emacs commands without modifier keys. It's similar to Vim's separation of command mode and insert mode.

All existing key bindings will work in God mode. It's only there to reduce your usage of modifier keys.
#+end_quote

[[https://github.com/emacsorphanage/god-mode][God-mode]] aims to ease keychord immision. You can easily switch it on/off via ~s-n~ shortcut. I use took inspiration from [[https://www.vim.org][vim]], so when in god-mode you can just hit ~i~ (to deactivate god-mode, something resembling the activation of /insert/ mode in vim) or ~u~ for /undo.

#+begin_src emacs-lisp
  (use-package god-mode
    :config
    (god-mode)
    (which-key-enable-god-mode-support)
    (global-set-key (kbd "s-n") 'god-local-mode)
    (define-key god-local-mode-map (kbd "i") 'god-local-mode)
    (define-key god-local-mode-map (kbd "u") 'undo)
    (define-key god-local-mode-map (kbd "U") 'keyboard-quit)
    (define-key god-local-mode-map (kbd ".") 'repeat)
    (define-key god-local-mode-map (kbd ">") 'end-of-buffer)
    (define-key god-local-mode-map (kbd "<") 'beginning-of-buffer)

    (setq god-exempt-major-modes (append god-exempt-major-modes '(
								  elfeed-search-mode
								  elfeed-show-mode
								  erc-mode
								  vterm-mode
								  )))

    (defun mm/god-mode-enabled ()
      (setq mm/god-mode-status 1)
      (setq cursor-type 'box))
    (defun mm/god-mode-disabled ()
      (setq mm/god-mode-status nil)
      (setq cursor-type 'bar))
    (add-hook 'god-mode-enabled-hook 'mm/god-mode-enabled)
    (add-hook 'god-mode-disabled-hook 'mm/god-mode-disabled))
#+end_src

* Versioning
** Magit

#+begin_src emacs-lisp
  (use-package magit
    :ensure t
    :config
    (transient-append-suffix 'magit-rebase "-d" '("-D" "Ingore date" "--ignore-date"))
    (transient-append-suffix 'magit-cherry-pick "-e" '("-n" "No commit" "--no-commit"))
    (global-set-key (kbd "C-x g") 'magit-status
                    ))
#+end_src

* Major modes
** Elisp

Main customizations for programming in ~elisp~.

#+begin_src emacs-lisp :tangle no
  (define-key emacs-lisp-mode-map (kbd "s-j") 'eval-print-last-sexp)
#+end_src

** Ruby

#+begin_src emacs-lisp
(use-package enh-ruby-mode)
(use-package rinari)
(use-package rspec-mode)
(use-package rvm)
(use-package bundler)
#+end_src

** Elixir
#+begin_src emacs-lisp
(use-package alchemist)
#+end_src
** Web

#+begin_src emacs-lisp
    (use-package web-mode
      :config
      (add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
      (add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
      (add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
      (add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
      (add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
      (add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
      (add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
      :custom
      (web-mode-enable-auto-indentation . nil))
#+end_src

Fast HTML typing with [[https://github.com/smihica/emmet-mode][Emmet-mode]].

#+begin_src emacs-lisp
  (use-package emmet-mode
    :config
    (add-hook 'sgml-mode-hook 'emmet-mode)
    (add-hook 'html-mode-hook 'emmet-mode)
    (add-hook 'web-mode-hook 'emmet-mode)
    (add-hook 'css-mode-hook  'emmet-mode))

#+end_src
** Markup
*** YAML
#+begin_src emacs-lisp
(use-package yaml-mode)
#+end_src
** COMMENT LSP mode
#+begin_src emacs-lisp
(use-package lsp-mode
  :init
  ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
;;  (setq lsp-keymap-prefix "C-c l")
  :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)
         (XXX-mode . lsp)
         ;; if you want which-key integration
         (lsp-mode . lsp-enable-which-key-integration))
  :commands lsp)

;; optionally
(use-package lsp-ui :commands lsp-ui-mode)
;; if you are helm user
(use-package helm-lsp :commands helm-lsp-workspace-symbol)
;; if you are ivy user
;;(use-package lsp-ivy :commands lsp-ivy-workspace-symbol)
;;(use-package lsp-treemacs :commands lsp-treemacs-errors-list)

;; optionally if you want to use debugger
(use-package dap-mode)
;; (use-package dap-LANGUAGE) to load the dap adapter for your language
#+end_src

* Org-mode

#+begin_src emacs-lisp
  (use-package org
    :bind
    (:map org-mode-map
	  ("M-p" . org-move-subtree-up)
	  ("M-n" . org-move-subtree-down))
    :config
    (add-to-list 'org-file-apps '(directory . emacs)))
#+end_src
*** Org-babel
**** Org src executions

     #+begin_src emacs-lisp
       (org-babel-do-load-languages 'org-babel-load-languages '(
								(shell . t)
(eshell .t)
								)
				    )
     #+end_src

** Beautify Org-mode

Beautify ~org-mode~ with bullets..

#+begin_src emacs-lisp
(use-package org-bullets
  :config
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+end_src

...and the mighty ~Olivetti~ mode!

#+begin_src emacs-lisp
(use-package olivetti
  :config
  (add-hook 'org-mode-hook 'olivetti-mode))
#+end_src

** Agenda

#+begin_src emacs-lisp
  (use-package org
    :custom
    (org-directory "~/Dropbox/org/")
    (org-agenda-files '("~/Dropbox/org/"))
    (org-default-notes-file "~/Dropbox/org/notes.org"))
#+end_src

Here a quick snippet to customize your [[https://orgmode.org/manual/Capture-templates.html][org capture templates]] (taken from [[http://www.howardism.org/Technical/Emacs/capturing-intro.html][www.howardism.org]]) and [[https://www.reddit.com/r/emacs/comments/7zqc7b/share_your_org_capture_templates/][here a reddit thread of shared org capture templates]].

#+begin_example emacs-lisp
 (add-to-list '(org-capture-templates
   '(("p" "Personal stuff")
     ("pt" "Scheduled task" entry
      (file+headline "~/Dropbox/org/notes.org" "Tasks")
      "** TODO %?\n%^t\n%i" :empty-lines 1)
     ("pn" "Note" entry
      (file "~/Dropbox/org/notes.org")
      "* %?\n%i"))))
#+end_example

*** Org capture

   Here's [[https://www.youtube.com/watch?v=qCdScs4YO8k&t=15s][Prot video]] about Org capture templates.
   

*** Alert

#+begin_src emacs-lisp
(use-package org-alert)
#+end_src
** COMMENT <<Blogging>>

[[org-mode]] has a built-in blogging feature under the ~ox-publish~
module. If you want to know more about Org-mode publishers,
[[https://orgmode.org/worg/exporters/ox-overview.html][check here]]. And here the fantastic blog of [[https://ag91.github.io/][ag91]] which use [[https://github.com/kelvinh/org-page][org-page]].

#+begin_src emacs-lisp :results output none :tangle no
  (require 'ox-publish)
  (let ((org-export-babel-evaluate nil)
	(org-publish-project-alist
	 '(("org-files"
	    :base-directory "./"
	    :base-extension "org"
	    :publishing-directory "~/site"
	    :recursive t
	    :publishing-function org-html-publish-to-html
	    :export-babel-evaluate nil
	    :headline-levels 4
	    :with-toc nil)
	   ("assets"
	    :base-directory "./assets/"
	    :base-extension "css\\|js\\|png\\|jpg\\|gif\\|pdf\\|mp3\\|ogg\\|swf"
	    :publishing-directory "~/site/assets/"
	    :recursive t
	    :publishing-function org-publish-attachment)
	   ("site" :components ("org-files" "assets")))))
    (org-publish "site"))
#+end_src

*** Autopublishing script.

#+begin_src emacs-lisp :results output none :tangle no
  (let* ((remote "git@github.com:MinasMazar/minasmazar.github.io.git")
	(commit-msg (concat "'Autopublish [" (current-time-string) "]'"))
	(out (shell-command-to-string "git remote"))
	(repo-p (string-match "fatal" out)))
    (cd "~/site")
    (unless repo-p (progn 
		     (shell-command "git init")
		     (shell-command (concat "git remote add origin " remote))))
    (shell-command "git add .")
    (shell-command (concat "git commit -m " commit-msg))
    (shell-command "git push origin master"))
#+end_src

* Applications
** Eww ~ web browser

#+begin_src emacs-lisp
  (use-package eww)

#+end_src

** Terminal emulators

Vterm imo is something you want if you need the most OS/temrinal like experience within emacs. It relies on vetrm libraries on your host system, which means to install this if you have MacOS/homeberw just

#+begin_src shell :tangle no :results output none
brew install libvterm
#+end_src

#+begin_src emacs-lisp
  (use-package vterm
    :init
    (defun vterm-or-create (&optional last-cmd)
      "Open *vterm* buffer if present, create a new one if none"
      (interactive "p")
      (vterm)
      (when (eq last-cmd 0)
        (progn
          (vterm-send-up)
          (vterm-send-return))))
    (defun vterm-send-last-cmd ()
      (interactive)
      (vterm-send-up)
      (vterm-send-return))
    :bind
    ("s-T" . vterm-or-create))
#+end_src

You can use vterm to spawn different processes

#+begin_example emacs-lisp
  #+begin_src emacs-lisp
    (with-current-buffer (vterm "*web-server*")
      (vterm-send-string "PORT=5000 bin/rails\n"))
    (with-current-buffer (vterm "*webpack-server*")
      (vterm-send-string "bin/webpack-dev-server \n"))
#+end_example

#+end_src
** Bongo
#+begin_src emacs-lisp
(use-package bongo)
#+end_src
** Try!

[[https://github.com/larstvei/Try][Try]] permits to one-shot try for some packages.

#+begin_src emacs-lisp
(use-package try)
#+end_src

**Here goes a list of packages that will be installed in a try version...**
** Networking
*** RESTClient
Restclient is a really useful tool, basically an emacs interface to ~curl~.

#+begin_src emacs-lisp
(use-package restclient)
(use-package ob-restclient
  :after org-mode)
#+end_src

Here an example of usage:

#+begin_example
# Set variables form elisp code using :=
:token := reaper-api-key
:account-id := reaper-account-id
:auth-headers = <<
User-Agent: curl
Authorization: Bearer :token
Harvest-Account-ID: :account-id
Content-Type: application/json
#

# Make API request to Harvest app
GET https://api.harvestapp.com/v2/users/me
:auth-headers
#+end_example

If you want your Emacs to interact to Harvest, you can use Reaper package!
** COMMENT News and RSS
*** Elfeed

#+begin_src emacs-lisp
  (use-package elfeed
    :config
    (add-to-list 'elfeed-feeds '(
				 "https://www.reddit.com/r/slackware/.rss"
				 "https://static.fsf.org/fsforg/rss/news.xml" . "open-source")))
#+end_src

    #+end_src

If you want to schedule RSS updates you can do something like:

#+begin_example emacs-lisp
  (run-at-time 10 (* 60 5) 'elfeed-update)
#+end_example

**** TODO Retrieve all Youtube feeds from your "channels" page

If you have a channel with this url ~https://www.youtube.com/channel/ID-OF-THE-CHANNEL~ the RSS feed for this channel will be ~https://www.youtube.com/feeds/videos.xml?channel_id=ID-OF-THE-CHANNEL~.
Here's a function to easy cast those urls.

#+begin_src emacs-lisp
  (defun mm/yt/channel-url-to-rss-url (&optional url)
    "Cast a Youtube channel URL to a RSS feed one"
    (interactive "sChannel URL: ")
    ;https://www.youtube.com/feeds/videos.xml?channel_id={ID}
    (message url))
#+end_src

* Mail
** [[http://www.offlineimap.org/][offlineimap]]

You can use Emacs as your mail client. In order to configure ~mu4e~ I'm following [[https://gist.github.com/areina/3879626][this useful gist]].
In order to let ~offlineimap~ to read your authfile, you must save this snippet into your ~~/.offlineimap.py~

#+BEGIN_EXAMPLE python
#!/usr/bin/python

import re, os

def get_password_emacs(machine, login, port):
    s = "machine %s login %s password ([^ ]*) port %s\n" % (machine, login, port)
    p = re.compile(s)
    authinfo = os.popen("gpg -q --no-tty -d ~/.authinfo.gpg").read()
    return p.search(authinfo).group(1)
#+END_EXAMPLE

and take care to add this entry to your ~~/.offlineimaprc~

#+BEGIN_EXAMPLE python
pythonfile = ~/.offlineimap.py
#+END_EXAMPLE

A normal ~~/.authfile.gpg~ with some entries for IMAP/SMTP account should be like this.

#+begin_example
machine imap.gmail.com login your-email@example.com password your-strong-password port imaps
machine imap.gmail.com login your-email@example.com password your-strong-password port 587
machine smtp.gmail.com login your-email@example.com password your-strong-password port 465
#+end_example

This is an example of an ~~/.offlineimaprc~ config file for a Gmail email account with the inclusion of ~offlineimap.py~ defined above.

#+begin_example
[general]
accounts = Gmail
maxsyncaccounts = 1
pythonfile = ~/.offlineimap.py

[Account Gmail]
localrepository = Local
remoterepository = Remote

[Repository Local]
type = Maildir
localfolders = ~/Maildir

[Repository Remote]
type = Gmail
remoteuser = your-email@gmail.com
remotepasseval = get_password_emacs("imap.gmail.com", "your-email@gmail.com", "993")
realdelete = no

folderfilter = lambda foldername: foldername not in ['[Gmail]/Spam', '[Gmail]/All Mail', '[Gmail]/Starred', '[Gmail]/Important']

holdconnectionopen = true
keepalive = 60
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
#+end_example

If you don't have a certificate you can generate via

#+begin_src sh
sudo mkcert -cert-file /etc/ssl/certs/ca-certificates.crt localhost
#+end_src

** [[https://www.djcbsoftware.nl/code/mu/mu4e.html][Mu4e]]

   Useful resources could be found [[https://www.djcbsoftware.nl/code/mu/mu4e/Gmail-configuration.html][here]].

Here we can't simply ~(use-package mu4e)~. On MacOS I've just soft-linked the ~/usr/local/Cellar/mu/1.4.15/share/emacs/site-lisp/mu/mu4e~
to ~~/.emacs.d/mu4e~.

Consider ~offlineimap~ could invoke indexing of ~mu~ (so setting the
~mu-binary~ could results in multiple invocations). Also the ~-o~ flag ("invoke once")
is required because otherwise it will stay active in background.

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/mu4e/")
  (require 'mu4e)
  (setq mu4e-update-interval (* 60 10)
	mu4e-mu-binary "/usr/local/bin/mu"
	mu4e-get-mail-command "/usr/local/bin/offlineimap -o"
	message-kill-buffer-on-exit t)

#+END_SRC

Sample setup of mu4e

#+begin_example emacs-lisp
(setq
   user-mail-address "USERNAME@gmail.com"
   user-full-name  "YOUR FULL NAME")
#+end_example

Here a sample configuration for SMTP

#+begin_example emacs-lisp
  (setq message-send-mail-function 'smtpmail-send-it
	smtpmail-stream-type 'starttls
	smtpmail-smtp-server "smtp.example.com"
	smtpmail-smtp-service 465
	smtpmail-stream-type 'ssl)
#+end_example

* Custom functions

Here I define some useful functions for daily use.

#+begin_src emacs-lisp
  (defun mm/yt-download (url &optional audio-only)
    "Download youtube video givin a URL"
    (interactive "sURL: ")
    (let* ((outbuff (format "*yt-download-%s*" url))
	  (audio-only (if current-prefix-arg current-prefix-arg 0))
	  (audio-only (if (< audio-only 0) "--extract-audio --audio-format mp3" ""))
	  (cmd (format "youtube-dl %s \"%s\"" audio-only url))
	  )
      (async-shell-command cmd outbuff)))
#+end_src

Now you can invoke the function and a URL will be asked.
* Private settings

I want to save my personal/private configuration into a separate,
private, not versioned file.

#+begin_src emacs-lisp
  (defvar mm/custom-file "~/.emacs.d/private.el"
    "My custom-not-versioned-private file")

  (if (file-exists-p mm/custom-file)
      (load mm/custom-file)
    (shell-command (format "touch %s" mm/custom-file)))
#+end_src

* EPG/GPG

This setting enables Emacs to ask pinentry via minibuffer.

#+begin_src emacs-lisp
(setq epa-pinentry-mode 'loopback)
#+end_src

* Appearance and theme
** COMMENT Tango dark
I load Tango dark by default

#+begin_src emacs-lisp
(load-theme 'tango-dark)
#+end_src

** COMMENT Modus vivendi (optional)

If you want the mighty [[https://protesilaos.com/modus-themes/][Modus Vivendi theme]] installed by default, uncomment this entry.

#+begin_src emacs-lisp
(use-package modus-vivendi-theme
  :config
  (load-theme 'modus-vivendi))
#+end_src

If you want a light mode, choose [[elisp:(call-interactively 'load-theme)][one of the list]] ;)

** Font size and zoom

You can customize default font face [[elisp:(customize-face 'default)][at runtime]].

If you save the configuration, you will find an entry like the next in
your ~init.el~ and can be runtime evaluated.

#+begin_example emacs-lisp
  (custom-set-faces
    ;; custom-set-faces was added by Custom.
    ;; If you edit it by hand, you could mess it up, so be careful.
    ;; Your init file should contain only one such instance.
    ;; If there is more than one, they won't work right.
    '(default ((t (:height 220)))))
#+end_example

** Modeline

Add an indicator of whether the God mode is active or not. First of all we should define a function that return a G if god-mode is active or an empy string if not.

#+begin_src emacs-lisp
(defun mm/mode-line-god-mode-indicator ()
   (if mm/god-mode-status " *G* " "i "))
#+end_src

Now add an entry to ~mode-line-format~ with something like

#+begin_src emacs-lisp
  (use-package emacs
    :config
    (add-to-list 'mode-line-format
		 '(:eval (mm/mode-line-god-mode-indicator))))
#+end_src

** Window rules
#+begin_example emacs-lisp
  (add-to-list 'display-buffer-alist '("\\*Help\\*"
					(display-buffer-in-side-window)
					(window-height . 0.25)
					(side . bottom)
					(slot . -1)))
  (add-to-list 'display-buffer-alist '("\\*Buffer List\\*"
					(display-buffer-in-side-window)
					(window-width . 0.25)
					(side . right)
					(sloq . -1)))
  (add-to-list 'display-buffer-alist '("dev.org"
					(display-buffer-in-side-window)
					(window-width . 0.35)
					(side . right)
					(sloq . -1)))
#+end_example
** Initial buffer (<<Homepage>>)

Emacs startup. You can easily customize ~initial-buffer-choice~
variable. I suggest you to set it as your /homepage/ kinda an
index/entry point or place where you usually start to think about my
daily work activities. It could be your *org-agenda* index, like [[file:emacs-home-page.org][this
example org-homepage]]. Consider it mapped on the pretty handy ~s-h~ shortcut.

#+begin_src emacs-lisp
  (global-set-key (kbd "s-h") '(lambda () (interactive)
				 (find-file initial-buffer-choice)))
#+end_src

** Dired

Easy copy to another dired buffer.. one of the killer feature of dired!

#+begin_src emacs-lisp
  (setq dired-dwim-target t)
  (add-hook 'dired-mode-hook #'dired-hide-details-mode)
#+end_src

Avoid opening many dired buffers.

#+begin_src emacs-lisp
  (use-package dired-single
    :after dired
    :bind
    (:map dired-mode-map (
                           ("RET" . 'dired-single-buffer)
                           ("s-N" . 'dired-single-up-directory)
                           )))
#+end_src

Dired subtree

#+begin_src emacs-lisp
  (use-package dired-subtree
    :after dired
    :bind
    (:map dired-mode-map ("<tab>" . dired-subtree-toggle)))

#+end_src
** Browser

Configure which broswer opens urls according to a match list. This is just an example (comment out to enable).

Define some customs for binary and arguments, like done for other browsers.

#+begin_src emacs-lisp
  (defcustom browse-url-opera-program "" "Opera executable")
  (defcustom browse-url-opera-arguments "opera" "Opera executable arguments")
  (setq browse-url-opera-arguments ())
#+end_src

Experimental.

#+begin_example emacs-lisp
(defun browse-url-ask (&optional browser url)
  (interactive "CBrowser: \n")
  (call-interactively browser url))
#+end_example
** [[https://www.opera.com/][Opera]] support

Define ~browse-url-opera~.

#+begin_src emacs-lisp
  (defun browse-url-opera (url &optional _new-window)
    "Ask the Opera WWW browser to load URL.
  Default to the URL around or before point.  The strings in
  variable `browse-url-opera-arguments' are also passed to
  Opera.
  The optional argument NEW-WINDOW is not used."
    (interactive (browse-url-interactive-arg "URL: "))
    (setq url (browse-url-encode-url url))
    (let* ((process-environment (browse-url-process-environment)))
      (apply 'start-process
	     (concat "opera " url) nil
	     browse-url-opera-program
	     (append
	      browse-url-opera-arguments
	      (list url)))))
#+end_src

This is an example mappging from ~url~ => ~browser~.

#+begin_example emacs-lisp
(setq browse-url-browser-function '(
				    ("twitter.com" . browse-url-opera)
				    ("github.com" . browse-url-chrome)
				    ("reddit.com" . eww-browse-url)
				    ("." . eww-browse-url)))

#+end_example
* Learning Emacs
** Regular Expression Syntax

Here is the syntax used by Emacs for regular expressions. Any character matches itself, except for the list below.

The following characters are special : . * + ? ^ $ \ [

Between brackets [], the following are special : ] - ^

Many characters are special when they follow a backslash – see below.

  .        any character (but newline)
  *        previous character or group, repeated 0 or more time
  +        previous character or group, repeated 1 or more time
  ?        previous character or group, repeated 0 or 1 time
  ^        start of line
  $        end of line
  [...]    any character between brackets
  [^..]    any character not in the brackets
  [a-z]    any character between a and z
  \        prevents interpretation of following special char
  \|       or
  \w       word constituent
  \b       word boundary
  \sc      character with c syntax (e.g. \s- for whitespace char)
  \( \)    start\end of group
  \< \>    start\end of word
  \_< \_>  start\end of symbol
  \` \'    start\end of buffer\string
  \1       string matched by the first group
  \n       string matched by the nth group
  \{3\}    previous character or group, repeated 3 times
  \{3,\}   previous character or group, repeated 3 or more times
  \{3,6\}  previous character or group, repeated 3 to 6 times
  \=       match succeeds if it is located at point
*?, +?, and ?? are non-greedy versions of *, +, and ? – see NonGreedyRegexp. Also, \W, \B, and \Sc match any character that does not match \w, \b, and \sc.

Characters are organized by category. Use C-u C-x = to display the category of the character under the cursor.

  \ca      ascii character
  \Ca      non-ascii character (newline included)
  \cl      latin character
  \cg      greek character
Here are some syntax classes that can be used between brackets, e.g. [[:upper:]\|[:digit:]\.].

  [:digit:]  a digit, same as [0-9]
  [:alpha:]  a letter (an alphabetic character)
  [:alnum:]  a letter or adigit (an alphanumeric character ()
  [:upper:]  a letter in uppercase
  [:space:]  a whitespace character, as defined by the syntax table
  [:xdigit:] an hexadecimal digit
  [:cntrl:]  a control character
  [:ascii:]  an ascii character
Syntax classes:

  \s-   whitespace character        \s/   character quote character
  \sw   word constituent            \s$   paired delimiter
  \s_   symbol constituent          \s'   expression prefix
  \s.   punctuation character       \s<   comment starter
  \s(   open delimiter character    \s>   comment ender
  \s)   close delimiter character   \s!   generic comment delimiter
  \s"   string quote character      \s|   generic string delimiter
  \s\   escape character

** Vectors
Get an element from a vector
#+BEGIN_SRC emacs-lisp
;; get a element from vector
(aref ["a" "b" "c"] 0) ; ⇒ "a"
;; get a element from vector
(elt ["a" "b" "c"] 0) ; ⇒ "a"
#+END_SRC
What's the difference between =aref= and =elt=?
=elt= is more general. It works on vector and list. But if you know
it's vector, you should use =aref=, because it's precise and faster.
** Timers
You can run specified function at specified time and with a specific timeout! Check out [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Timers.html][the doc]] for more information.

#+BEGIN_QUOTE
The list-timers command lists all the currently active timers. There’s
only one command available in the buffer displayed: c
(timer-list-cancel) that will cancel the timer on the line under
point.
#+END_QUOTE
* Credits
  I would like to thanks:
- [[http://kelvinh.github.io/][Kelvin Hu]] for his [[https://github.com/kelvinh/.emacs.d][emacs configuration]] and the idea to write it in a *literate style*.
- [[http://www.howardism.org/][Howard Abrams]] for his [[https://github.com/howardabrams/dot-files][dotfiles]].
- [[https://github.com/aaronbieber][Aaron Bieber]] for his dotfiles and for the wonderful speech [[https://www.youtube.com/watch?v%3DJWD1Fpdd4Pc][Evil Mode: Or, How I Learned to Stop Worrying and Love Emacs]] that makes me *fall in love* with Emacs. ;-)
- [[https://protesilaos.com/][Protesilaos Stavrou]] for his [[https://protesilaos.com/dotemacs/][comprehensive "dotemacs" (.emacs) for GNU/Linux]] and [[https://protesilaos.com/codelog/][the huge amount of posts and videos about Emacs]].
- [[https://github.com/sponsors/daviwil][David Wilson]] for his fantastic [[https://www.youtube.com/channel/UCAiiOTio8Yu69c3XnR7nQBQ][System Crafters screencasts]]!
- [[http://staff.science.uva.nl/~dominik/][Carsten Dominik]], creator of the mighty [[http://orgmode.org][org-mode]]. <<org-mode>>
- [[http://ehneilsen.net][Eric H. Neilsen, Jr.]] for his wonderful  [[http://ehneilsen.net/notebook/orgExamples/org-examples.html][org-mode examples and cookbook]].
- [[https://www.gnu.org/software/emacs/][The Emacs editor]] and his *guru* [[https://stallman.org/][Richard Stallman]].
- [[https://www.gnu.org/software/emacs/manual/pdf/emacs-lisp.pdf][The Elisp documentation]]
