#+TITLE: Minemacs
#+AUTHOR: MinasMazar
#+EMAIL: minasmazar@gmail.com
#+DATE: <2024-08-08 Thu>
#+STARTUP: show2levels
#+PROPERTY: header-args :tangle (file-name-concat user-emacs-directory "init.el")
#+SETUPFILE: ../../../templates/_header.org

* Emacs configuration
** Minemacs

#+begin_src emacs-lisp
  ;; Minemacs helpers
  ;;

  (defun minemacs-tangle-if-not-disabled (module)
    (let ((dest-file (file-name-concat (minemacs-modules-directory) module)))
      (if (member-ignore-case "disable" (org-get-tags)) "no" dest-file)))

  (defun minemacs-subdir (path)
    (file-name-concat user-emacs-directory path))

  (defun minemacs-modules-directory ()
    (minemacs-subdir "modules"))

  (defun minemacs-custom-file ()
    (file-name-concat user-emacs-directory "custom.el"))

  (defun minemacs-modules-load (&optional matcher)
    "Load all modules '*.el' files in 'minemacs-modules-directory'"
    (interactive)
    (if (file-readable-p (minemacs-modules-directory))
	(let ((matcher (format "%s\.el$" (or matcher "."))))
	  (mapcar (lambda (file)
		    (load file 'noerror))
		  (directory-files (minemacs-modules-directory) t matcher)))))
#+end_src

** Package initialization

More info about =load-path= at https://www.emacswiki.org/emacs/LoadPath. Most of this initial setup is inspired by [[https://protesilaos.com/codelog/2024-11-28-basic-emacs-configuration][Protesilaos setup configuration]].

#+begin_src elisp
  (let* ((vendor (minemacs-subdir "vendor"))
	 (default-directory vendor))
    (add-to-list 'load-path vendor)
    (and (file-readable-p vendor) (normal-top-level-add-subdirs-to-load-path)))

  (require 'package)
  (package-initialize)
  (setq use-package-always-ensure t
	package-archives '(
			   ("melpa" . "https://melpa.org/packages/")
			   ("elpa" . "https://elpa.gnu.org/packages/")
			   ("nongnu" . "https://elpa.nongnu.org/nongnu/")
			   ))

  (when (< emacs-major-version 29)
    (unless (package-installed-p 'use-package)
      (unless package-archive-contents
	(package-refresh-contents))
      (package-install 'use-package)))
#+end_src

** Basic settings

#+begin_src elisp
  (use-package emacs
    :ensure nil
    :defer
    :hook
    (after-init . toggle-frame-maximized)
    (dired-mode . dired-hide-details-mode)
    :custom
    (dired-dwim-target t)
    (dired-listing-switches "-alth")
    ;; (completion-auto-help nil)
    (enable-recursive-minibuffers t)
    (initial-buffer-choice #'eshell)
    (make-backup-files nil)
    (shr-inhibit-images t)
    (tab-always-indent 'complete)
    (use-short-answers t)
    :config
    (tool-bar-mode -1)
    (menu-bar-mode -1)
    (scroll-bar-mode -1)
    (savehist-mode 1)
    (recentf-mode 1)
    (ffap-bindings)
    (repeat-mode 1)
    (server-start 1)
    ;; (fido-vertical-mode 1)

    ;; Shared configuration
    (if (file-exists-p "~/Dropbox/minemacs/")
	(setq bookmark-file "~/Dropbox/minemacs/bookmarks"
	      eshell-aliases-file "~/Dropbox/minemacs/eshell-aliases"
	      custom-file (minemacs-custom-file)))

    (global-set-key (kbd "s-0") (kbd "C-x 0"))
    (global-set-key (kbd "s-1") (kbd "C-x 1"))
    (global-set-key (kbd "s-2") (kbd "C-x 2"))
    (global-set-key (kbd "s-3") (kbd "C-x 3"))

    (setq minemacs-map
      (let ((map (make-sparse-keymap)))
	(define-key map (kbd "a") #'org-agenda)
	(define-key map (kbd "k") #'org-capture)
	(define-key map (kbd "e") #'eshell)
	(define-key map (kbd "E")
		    (lambda (command)
		      (interactive "sEmacs eshell command: ")
		      (eshell-command command current-prefix-arg)))
	(define-key map (kbd "r") #'recentf)
	(define-key map (kbd "8") #'emoji-search)
	(define-key map (kbd "w j") #'webjump)
	(define-key map (kbd "w w") #'eww)
	map))

    :bind-keymap
    ("s-o" . minemacs-map)
    :bind
    ("s-k" . #'execute-extended-command)
    ("s-n" . #'god-local-mode)
    ("s-w" . #'other-window)
    ("s-)" . #'kill-current-buffer)
    ("s-p" . #'project-switch-to-buffer)
    ("s-P" . #'project-find-file)
    ("s-[" . #'previous-buffer)
    ("s-]" . #'next-buffer)
    ("s-N" . #'dired-jump)
    ("s-e" . #'dabbrev-expand)
    ("s-r" . #'repeat)
    ("s-i" . #'imenu)
    ("s-b" . #'ibuffer)
    ("s-j" . #'switch-to-buffer)
    ("s-t" . #'rgrep)
    ("s--" . #'bookmark-jump)
    ("s-_" . #'bookmark-set)
    (:map key-translation-map
	  ("s-m" . "\C-x")
	  ("s-M" . "\C-c"))
    (:map isearch-mode-map
	  ("C-p" . #'isearch-repeat-backward)
	  ("C-n" . #'isearch-repeat-forward)
	  ("<tab>" . #'isearch-repeat-forward)
	  ("<S-tab>" . #'isearch-repeat-backward))
    (:map completion-list-mode-map
	  ("e" . #'switch-to-minibuffer)))
#+end_src

** Minibuffer

#+begin_src elisp
  (use-package orderless :custom (completion-styles '(orderless)))
  (use-package vertico :config (vertico-mode 1))
#+end_src

** Modal editing

#+begin_src elisp
  (use-package god-mode
    :after emacs
    :demand
    :init
    (defun minemacs-god-mode-line ()
      (if god-mode "⛪" " "))

    (defun minemacs-god-mode-disabled ()
      (setq cursor-type 'bar))

    (defun minemacs-god-mode-enabled ()
      (setq cursor-type 'box))

    :hook ((god-mode-enabled . minemacs-god-mode-enabled)
	 (god-mode-disabled . minemacs-god-mode-disabled))
    :bind
    ("s-n" . #'god-local-mode)
    (:map god-local-mode-map
     ("i" . #'god-local-mode)
     ("I" . #'org-edit-special)
     ("u" . #'undo)
     ("U" . #'undo-redo)
     ("<" . #'beginning-of-buffer)
     (">" . #'end-of-buffer)
     ("[" . #'backward-paragraph)
     ("]" . #'forward-paragraph))
    :config
    (god-local-mode))
#+end_src

** Auto-completion

#+begin_src elisp
  (use-package corfu
    :hook
    (eshell-mode . (lambda ()
		     (setq-local corfu-auto nil)
		     (corfu-mode)))
    :custom
    (corfu-cycle t)
    :config
    (global-corfu-mode))
#+end_src

#+begin_src elisp
  (use-package cape
    :init
    (add-hook 'completion-at-point-functions #'cape-file)
    (add-hook 'completion-at-point-functions #'cape-elisp-block)
    (add-hook 'completion-at-point-functions #'cape-elisp-symbol)
    (add-hook 'completion-at-point-functions #'cape-history)
    (add-hook 'completion-at-point-functions #'cape-line)
    (add-hook 'completion-at-point-functions #'cape-dabbrev))
    ;;(add-hook 'completion-at-point-functions #'cape-keyword)
    ;;(add-hook 'completion-at-point-functions #'cape-tex)
    ;;(add-hook 'completion-at-point-functions #'cape-sgml)
    ;;(add-hook 'completion-at-point-functions #'cape-rfc1345)
    ;;(add-hook 'completion-at-point-functions #'cape-abbrev)
    ;;(add-hook 'completion-at-point-functions #'cape-dict)

#+end_src

** Embark

#+begin_src elisp
  (use-package embark
    :after god-mode
    :demand
    :config
    (add-to-list 'god-exempt-major-modes 'embark-mode)
    :bind*
    ("C-," . embark-act)
    (:map embark-general-map
	  ("C-w" . browse-url))
    (:map embark-identifier-map
	  ("R" . query-replace)
	  ("O" . multi-occur-in-matching-buffers)
	  ("c" . browse-url-chrome)
	  ("f" . browse-url-firefox))
    (:map embark-url-map
	  ("c" . browse-url-chrome)
	  ("f" . browse-url-firefox))
    (:map  embark-file-map
	   ("p" . project-find-file)
	   ("b" . project-switch-to-buffer)
	   ("," . append-to-previous-buffer)))
#+end_src

** Load modules and custom configurations

#+begin_src elisp
  (load custom-file :no-error-if-file-is-missing)
  (minemacs-modules-load)
#+end_src

* On hand documentation
:PROPERTIES:
:header-args: :tangle no
:END:
** [[https://raw.githubusercontent.com/emacs-tw/awesome-elisp/refs/heads/master/README.org][Awesome Elisp]]
** Online documentation for [[http://orgmode.org][org-mode 🦄]] and [[https://orgmode.org/worg/][worg 🌈]]
** Other Commands, functions, variables, keybindings

Just press ~C-h o~ to get help on those symbols.

- =add-file-local-variable= (append at bottom of the file) and =add-file-local-variable-prop-line= (prepend in the first line)
- =align-regexp=
- =auto-mode-alist=
- =browse-url-of-buffer=
- =command-switch-alist=
- =completions-max-height=
- =completion-auto-help=
- =compilation-scroll-output=
- =current-time-string=
- =dired-guess-shell-alist-user=
- =display-time-day-and-date=
- =display-time-mode=
- =epa-pinentry-mode=
- =format-time-string=
- =describe-text-properties=
- =face-remap-add-relative= and =face-remap-remove-relative= to easily modify faces in current buffer
- =find-name-dired=
- =frame-title-format=
- =image-crop=
- =imenu-generic-expression=
- =json-pretty-print-buffer=
- =make-list= and =number-sequence=
- =mm-discouraged-alternatives=
- =org-agenda-include-diary=
- =org-agenda-custom-commands=
- =org-archive-subtree-default=
- =org-babel-load-file=
- =org-todo-keywords=
- =pp-eval-expression=
- =proced=
- =project-switch-commands=
- =shr-inhibit-images=
- =string-match=
- ~C-x @~ prefix allow to reach/remap alt/super/Hyper keys

** [[info:org#Working with Source Code][Org code-blocks]]

#+begin_example org
,#+BEGIN_SRC sh :var filename=(buffer-file-name) :exports both
  wc -w $filename
,#+END_SRC
#+end_example

** String and Symbols

#+begin_src elisp
(symbol-name 'some-symbol)
; => "some-symbol"
(intern "some-symbol")
; => some-symbol
#+end_src

** Macros

#+begin_src elisp
  (defmacro ++ (x)
    (list 'setq x (list '1+ x)))
#+end_src

** Vectors

Get an element from a vector

#+begin_example emacs-lisp
;; get a element from vector
(aref ["a" "b" "c"] 0) ; ⇒ "a"
;; get a element from vector
(elt ["a" "b" "c"] 0) ; ⇒ "a"
#+end_example

What's the difference between =aref= and =elt=?
=elt= is more general. It works on vector and list. But if you know
it's vector, you should use =aref=, because it's precise and faster.

** Handle List

To find an element

- =member=
- =contains=
- =seq-find=

#+begin_example elisp
  (seq-find (lambda (val) (= 3 val)) '(1 2 3))
#+end_example

** Ibuffer

To occur among marked buffers in =ibuffer= press ~O~.

** Imenu
** Eshell

Download four random images from picsum using an index.

#+begin_src elisp
  for i in $(number-sequence 1 4) { wget -O wallpaper_$1.jpg https://picsum.photos/1920/1080.jpg }
#+end_src

** EWW ~ experimenting with =eww-retrieve-command=

Possible values for this variable could be
=chrome --headless --disable-gpu --dump-dom --profile-directory=Default https://stackoverflow.com/=

** (interactive) functions

Refs to [[https://emacs.stackexchange.com/questions/32248/how-to-write-a-function-with-an-interactive-choice-of-the-value-of-the-argument][this SO post]] try [[elisp:(completing-read "Prompt: " '(i1 i2 i3))]] and [[https://emacsdocs.org/docs/elisp/Text-from-Minibuffer][this post]]; try [[elisp:(read-from-minibuffer "Prompt: " "initial")]]. Take a look at =minemacs/demo-function=, it can help if you want to write functions with bit more complex interactive prompts.

#+begin_example emacs-lisp
  (defun minemacs/demo-function (url &optional handler)
    "Example function."
    (interactive (list
		  (read-from-minibuffer "URL: ")
		  (completing-read "handler: " '(browse-url-firefox browse-url-chrome))))
     (message (format "url: %s, handler: %s" url handler )))
#+end_example

** Regular Expression Syntax (regexp)

You can use the wonderful tool =regexp-builder=. Use =string-match= to run a regexp and =match-string= to extract the captures (remember to specify the 2nd arugment as the matched string itself). Example:

#+begin_example elisp
(let ((match-data (string-match "\\(\\ca\\{11\\}\\)\$" "https://www.youtube.com/watch?v=JvBfP62HTAM")))
  (match-string 1 "https://www.youtube.com/watch?v=JvBfP62HTAM"))
#+end_example

#+begin_quote
Here is the syntax used by Emacs for regular expressions. Any character matches itself, except for the list below.

The following characters are special : . * + ? ^ $ \ [

Between brackets [], the following are special : ] - ^

Many characters are special when they follow a backslash – see below.

  .        any character (but newline)
  *        previous character or group, repeated 0 or more time
  +        previous character or group, repeated 1 or more time
  ?        previous character or group, repeated 0 or 1 time
  ^        start of line
  $        end of line
  [...]    any character between brackets
  [^..]    any character not in the brackets
  [a-z]    any character between a and z
  \        prevents interpretation of following special char
  \|       or
  \w       word constituent
  \b       word boundary
  \sc      character with c syntax (e.g. \s- for whitespace char)
  \( \)    start\end of group
  \< \>    start\end of word
  \_< \_>  start\end of symbol
  \` \'    start\end of buffer\string
  \1       string matched by the first group
  \n       string matched by the nth group
  \{3\}    previous character or group, repeated 3 times
  \{3,\}   previous character or group, repeated 3 or more times
  \{3,6\}  previous character or group, repeated 3 to 6 times
  \=       match succeeds if it is located at point
*?, +?, and ?? are non-greedy versions of *, +, and ? – see NonGreedyRegexp. Also, \W, \B, and \Sc match any character that does not match \w, \b, and \sc.

Characters are organized by category. Use C-u C-x = to display the category of the character under the cursor.

  \ca      ascii character
  \Ca      non-ascii character (newline included)
  \cl      latin character
  \cg      greek character
Here are some syntax classes that can be used between brackets, e.g. [[:upper:]\|[:digit:]\.].

  [:digit:]  a digit, same as [0-9]
  [:alpha:]  a letter (an alphabetic character)
  [:alnum:]  a letter or adigit (an alphanumeric character ()
  [:upper:]  a letter in uppercase
  [:space:]  a whitespace character, as defined by the syntax table
  [:xdigit:] an hexadecimal digit
  [:cntrl:]  a control character
  [:ascii:]  an ascii character
Syntax classes:

  \s-   whitespace character        \s/   character quote character
  \sw   word constituent            \s$   paired delimiter
  \s_   symbol constituent          \s'   expression prefix
  \s.   punctuation character       \s<   comment starter
  \s(   open delimiter character    \s>   comment ender
  \s)   close delimiter character   \s!   generic comment delimiter
  \s"   string quote character      \s|   generic string delimiter
  \s\   escape character
#+end_quote

** Timers

You can run specified function at specified time and with a specific timeout. Check out [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Timers.html][the doc]] for more information.

#+BEGIN_EXAMPLE elisp
(run-at-time "11 min" t #'elfeed-update)
(run-at-time "5 hours" t (lambda () (load-theme (seq-random-elt custom-known-themes))))
#+END_EXAMPLE

#+BEGIN_QUOTE
The list-timers command lists all the currently active timers. There’s
only one command available in the buffer displayed: c
(timer-list-cancel) that will cancel the timer on the line under
point.
#+END_QUOTE

** Insert colorize text programmatically

#+begin_example elisp
(insert (propertize "Red Text" 'font-lock-face '(:foreground "red")))
#+end_example

** Buffer management

Code stolen from [[https://stackoverflow.com/questions/4886745/emacs-what-is-the-shortcut-key-to-clear-buffer][stackoverflow]].

#+begin_src emacs-lisp :tangle no
(defun minemacs-clear-buffer ()
  "clear whole buffer add contents to the kill ring"
  (interactive)
  (kill-region (point-min) (point-max)))

(defun minemacs-clear-buffer-permenantly ()
  "clear whole buffer, contents is not added to the kill ring"
  (interactive)
  (delete-region (point-min) (point-max)))
#+end_src

** Faces and fonts

If you'd like to have a smaller font on compialtion buffers

#+begin_src elisp
  (add-hook 'compilation-mode-hook (lambda () (text-scale-decrease 1)))
#+end_src

Useful function if you want to quick inspect the face under cursor

#+begin_src elisp
  (defun what-face (pos)
    (interactive "d")
    (let ((face (or (get-char-property pos 'read-face-name)
                    (get-char-property pos 'face))))
      (if face (message "Face: %s" face) (message "No face at %d" pos))))
#+end_src

Get the list of font families =(font-family-list)=; here's the code to set a random font family in the current frame.

#+begin_src elisp
  (set-face-font 'default (seq-random-elt (font-family-list)))
#+end_src
** Libaries

- [[https://tkf.github.io/emacs-request/][request.el]]

** Useful topics
- [[https://www.masteringemacs.org/article/mastering-key-bindings-emacs][Mastering Key-Bindings in Emacs]]
- [[https://orgmode.org/manual/Results-of-Evaluation.html][Results of Evaluation]]
- [[https://dev.to/rajasegar/5-ways-to-get-text-from-an-emacs-buffer-4c3l][5 ways to get text from an Emacs buffer]]

  #+begin_example elisp
    (let ((start (point-min))
	  (end (point-max)))
      (buffer-substring start end))
  #+end_example
* Credits

I would like to thanks:
- [[http://kelvinh.github.io/][Kelvin Hu]] for his [[https://github.com/kelvinh/.emacs.d][emacs configuration]] and the idea to write it in a *literate style*.
- [[http://www.howardism.org/][Howard Abrams]] for his [[https://github.com/howardabrams/dot-files][dotfiles]].
- [[https://github.com/aaronbieber][Aaron Bieber]] for his dotfiles and for the wonderful speech [[https://www.youtube.com/watch?v=JWD1Fpdd4Pc][Evil Mode: Or, How I Learned to Stop Worrying and Love Emacs]] that makes me *fall in love* with Emacs. ;-)
- [[https://protesilaos.com/][Protesilaos Stavrou]] for his [[https://protesilaos.com/dotemacs/][comprehensive "dotemacs" (.emacs) for GNU/Linux]] and [[https://protesilaos.com/codelog/][the huge amount of posts and videos about Emacs]].
- [[https://github.com/sponsors/daviwil][David Wilson]] for his fantastic [[https://www.youtube.com/channel/UCAiiOTio8Yu69c3XnR7nQBQ][System Crafters screencasts]]!
- [[http://staff.science.uva.nl/~dominik/][Carsten Dominik]], creator of [[http://orgmode.org][org-mode]] 🦄
- [[https://gitlab.com/spudlyo][Mike Hamrick]] for [[https://gitlab.com/spudlyo/orgdemo2][orgdemo2]] which is really useful if you want learn a lot of stuff about =org-mode=.
- [[http://ehneilsen.net][Eric H. Neilsen, Jr.]] for his wonderful  [[http://ehneilsen.net/notebook/orgExamples/org-examples.html][org-mode examples and cookbook]].
- [[https://www.omarpolo.com/][Omar Polo]] and [[https://ict4g.net/adolfo/index.html][Adolfo Villafiorita]]
- [[http://xahlee.info/emacs/emacs/emacs.html][Xah Lee Web]]
