#+TITLE: MinasMazar's blog ~ dev stuff
#+AUTHOR: MinasMazar
#+EMAIL: minasmazar@gmail.com
#+DATE: <2024-01-31 Wed>
#+STARTUP: overview

* Docker
** Backup and port Postgres databases across images

Bind to
#+begin_src sh
  docker run --rm --name postgres --volume ~/postgres-data:/var/lib/postgresql/data postgres:latest
#+end_src

Backup volume with

#+begin_src eshell
  tar cf postgres-data_$(format-time-string "%N").tar postgres-data
#+end_src

** Disable/enable autostart of a docker container.

#+begin_src sh
docker update --restart [no|unless-stopped] <docker-container>
#+end_src

** Playing Sound in Docker Containers ([[https://prateeksrivastav598.medium.com/playing-sound-in-docker-containers-a-step-by-step-guide-f7a06e246a35][here the source article]])

#+begin_src sh
  docker run --rm -it --privileged=true --device=/dev/snd:/dev/snd audio-container:v1
#+end_src

** Rename a docker image

#+begin_src sh
  docker tag OldName:tag NewName:tag
#+end_src

** Rename a docker container

#+begin_src sh
  sudo docker rename oldname_app newname_app
#+end_src

** Installing Docker on Raspberry PI

Follow [[https://docs.docker.com/engine/install/raspberry-pi-os/#install-using-the-repository][the instructions in the Docker documentation]]. Before you can install Docker Engine, you need to uninstall any conflicting packages. Distro maintainers provide an unofficial distributions of Docker packages in APT. You must uninstall these packages before you can install the official version of Docker Engine.

#+begin_src sh
  #!/bin/bash

  # Uninstall unofficial distributions of Docker packages in APT

  sudo apt-get purge docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-ce-rootless-extras

  # Remove images, containers, volumes, or custom configuration files 

  sudo rm -rf /var/lib/docker
  sudo rm -rf /var/lib/containerd

  # Add Docker's official GPG key:
  sudo apt-get update
  sudo apt-get install ca-certificates curl
  sudo install -m 0755 -d /etc/apt/keyrings
  sudo curl -fsSL https://download.docker.com/linux/raspbian/gpg -o /etc/apt/keyrings/docker.asc
  sudo chmod a+r /etc/apt/keyrings/docker.asc

  # Set up Docker's APT repository:
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/raspbian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  sudo apt-get update

  # Install Docker packages
  sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  # Verify that the installation is successful by running the hello-world image:
  sudo docker run hello-world
#+end_src

Remember to keep the Build and App images in sync (see [[https://github.com/teslamate-org/teslamate/issues/3691#issuecomment-1966074893][here]])

When building an image, you can see an error like /cannot find the image for the platform.../. Consider to add =--platform arm64= flag to the =docker build= command. [[https://docs.docker.com/reference/cli/docker/buildx/build/#platform][Here's the official Docker documentation]] for this flag. Also keep an eye [[https://github.com/containerd/containerd/blob/v1.4.3/platforms/platforms.go#L63][to this file]] to get a list of platforms. Remember you can detect the platform of the current machine via =uname -a=.

If you're using Docker to run Elixir, you can face an error like this during the dependencies compilation:

#+begin_src sh
could not compile dependency :ssl_verify_fun, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ssl_verify_fun", update it with "mix deps.update ssl_verify_fun" or clean it with "mix deps.clean ssl_verify_fun"
#+end_src

In this case, install the =erlang-public-key= package should solve the issue.


The Raspbian issue: another error that can occur while building a docker image on Raspbian that uses =apt-get= commands is

#+begin_src sh
  ERROR: failed to solve: process "/bin/sh -c apt-get update -y &&   apt-get install -y libstdc++6 openssl libncurses5 locales ca-certificates &&   apt-get clean && rm -f /var/lib/apt/lists/*_*" did not complete successfully: exit code: 159
#+end_src

It seems there's a problem with [[https://github.com/moby/moby/issues/40734][libseccomp]]; according to [[https://askubuntu.com/questions/1263284/apt-update-throws-signature-error-in-ubuntu-20-04-container-on-arm][this SO thread]] the solution is to upgrade libseccomp manually **on the host system**: download [[https://packages.debian.org/sid/libseccomp2][here]] and =sudo dpkg -i libseccomp2_2.4.3-1+b1_armhf.deb=.

** Usefull links for troubleshooting

- https://github.com/teslamate-org/teslamate/issues/3691
  
** [[Dockerize Phoenix webapp (my_app)]]
* Icons

- https://remixicon.com/

* Git

How do I change the author and committer name/email for multiple commits?

#+begin_src sh
  git rebase -r a5bf6c2 --exec 'git commit --amend --no-edit --reset-author'
#+end_src

* Pulseaudio

You can refer this interesting [[https://askubuntu.com/questions/71863/how-to-change-pulseaudio-sink-with-pacmd-set-default-sink-during-playback][SO thread]].

#+begin_src sh
  pacmd help list-sinks
  pacmd list-sink-inputs
  pacmd move-sink-input 5 1
#+end_src

* Alsamixer

Toggle mute

#+begin_src sh
  amixer set Master toggle
#+end_src

* [[https://it.wikipedia.org/wiki/Crontab][Crontab]]

If you need to write a crontab entry you can use https://crontab.guru/

* [[https://elixir-lang.org/][Elixir]]
** Resources

- [[https://elixir-toolbox.dev/][Toolbox]]
- [[https://dorgan.ar/posts/2021/04/the_elixir_ast/][Metaprogramming: The Elixir AST]]
- [[https://joyofelixir.com/17-mix-dependencies][Mix dependencies]]

** GenServer template

#+begin_src elixir
  defmodule MyApp.Server do
    use GenServer

    def start_link(args) do
      GenServer.start_link(__MODULE__, args, name: Map.get(args, :name, __MODULE__))
    end

    def init(_) do
      {:ok, []}
    end
  end
#+end_src

** DynamicSupervsior template

#+begin_src elixir
  defmodule MySupervisor do
    use DynamicSupervisor
    
    def start_link(init_arg) do
      DynamicSupervisor.start_link(__MODULE__, init_arg, name: __MODULE__)
    end
    
    def start_child(foo, bar, baz) do
      # If MyWorker is not using the new child specs, we need to pass a map:
      # spec = %{id: MyWorker, start: {MyWorker, :start_link, [foo, bar, baz]}}
      spec = {MyWorker, foo: foo, bar: bar, baz: baz}
      DynamicSupervisor.start_child(__MODULE__, spec)
    end
    
    @impl true
    def init(init_arg) do
      DynamicSupervisor.init(
        strategy: :one_for_one,
        extra_arguments: [init_arg]
      )
    end
  end
#+end_src

** example KV server

#+begin_src elixir
  defmodule Darbula.KV do
    use Agent

    def start_link do
      Agent.start_link(fn -> %{} end, name: __MODULE__)
    end

    def get(key) do
      Agent.get(__MODULE__, fn store -> Map.get(store, key) end)
    end

    def set(key, value) do
      with :ok <- Agent.update(__MODULE__, fn store -> Map.put(store, key, value) end) do
        value
      end
    end

    def get_or_set(key, fun) when is_function(fun) do
      get(key) || set(key, fun.())
    end
  end
#+end_src

** example :dets persist wrapper

#+begin_src elixir
  defmodule Mixer.Persist do
    use GenServer

    @table_name :mixer_persist

    def start_link(table_name) do
      GenServer.start_link(__MODULE__, table_name, name: __MODULE__)
    end

    def init(table_name) do
      {:ok, _} = :dets.open_file(table_name || @table_name, [])
    end

    def get(table_name \\ @table_name, key) do
      case :dets.lookup(table_name, key) do
        [{^key, value}] -> value
        [] -> nil
      end
    end

    def set(table_name \\ @table_name, key, value) do
      :dets.insert(table_name, {key, value}) && value
    end

    def get_or_set(table_name \\ @table_name, key, fun) when is_function(fun) do
      get(table_name, key) || set(table_name, key, fun.())
    end
  end
#+end_src

** Development Tools: Makefile
#+begin_src makefile
  default: t c

  c:
  	iex -S mix
  t:
  	mix test
  tt:
  	mix test --listen-on-stdin
  reset:
  	mix do deps.get, deps.compile, compile
  	make c
#+end_src
** Install Elixir on Raspberry/Raspbian (source article [[https://erlangsolutions.medium.com/installing-elixir-on-a-raspberry-pi-the-easy-way-22f347a77e2c][here]]).

#+begin_src sh
  sudo apt-get update && sudo apt-get install erlang erlang-dev elixir
#+end_src

** Dockerize Phoenix webapp (my_app)
*** Dockerfile

More info on [[Docker][Docker here]].

#+begin_src yml
# Find eligible builder and runner images on Docker Hub. We use Ubuntu/Debian
# instead of Alpine to avoid DNS resolution issues in production.
#
# https://hub.docker.com/r/hexpm/elixir/tags?page=1&name=ubuntu
# https://hub.docker.com/_/ubuntu?tab=tags
#
# This file is based on these images:
#
#   - https://hub.docker.com/r/hexpm/elixir/tags - for the build image
#   - https://hub.docker.com/_/debian?tab=tags&page=1&name=bullseye-20230227-slim - for the release image
#   - https://pkgs.org/ - resource for finding needed packages
#   - Ex: hexpm/elixir:1.15.0-erlang-26.0-debian-bullseye-20230227-slim
#
ARG ELIXIR_VERSION=1.16.2
ARG OTP_VERSION=26.1.2
ARG DEBIAN_VERSION=bullseye-20240423-slim

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"
ARG RUNNER_IMAGE="debian:${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE} as builder

# install build dependencies
RUN apt-get update -y && apt-get install -y build-essential git \
    && apt-get clean && rm -f /var/lib/apt/lists/*_*

# prepare build dir
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# set build ENV
ENV MIX_ENV="prod"

# install mix dependencies
COPY mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV
RUN mkdir config

# copy compile-time config files before we compile dependencies
# to ensure any relevant config change will trigger the dependencies
# to be re-compiled.
COPY config/config.exs config/${MIX_ENV}.exs config/
RUN mix deps.compile

COPY priv priv

COPY lib lib

COPY assets assets

# compile assets
RUN mix assets.deploy

# Compile the release
RUN mix compile

# Changes to config/runtime.exs don't require recompiling the code
COPY config/runtime.exs config/

COPY rel rel
RUN mix release

# start a new build stage so that the final image will only contain
# the compiled release and other runtime necessities
FROM ${RUNNER_IMAGE}

RUN apt-get update -y && \
  apt-get install -y libstdc++6 openssl libncurses5 locales ca-certificates \
  && apt-get clean && rm -f /var/lib/apt/lists/*_*

# Set the locale
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

WORKDIR "/app"
RUN chown nobody /app

# set runner ENV
ENV MIX_ENV="prod"

# Only copy the final release from the build stage
COPY --from=builder --chown=nobody:root /app/_build/${MIX_ENV}/rel/my_app ./

USER nobody

# If using an environment that doesn't automatically reap zombie processes, it is
# advised to add an init process such as tini via `apt-get install`
# above and adding an entrypoint. See https://github.com/krallin/tini for details
# ENTRYPOINT ["/tini", "--"]

CMD ["/app/bin/server"]
#+end_src

*** Docker compose

#+begin_src yml
# Version of docker-compose.
version: '3'

# Containers we're going to run.
name: my_app

services:
   # Our Phoenix container.
   phoenix:
      # The build parameters for this container.
      build:
         # Here we define that it should build from the current directory.
         context: .
      environment:
         # Variables to connect to our Postgres server.
         DATABASE_URL: ecto://postgres:postgres@db:5432/my_app
         MIX_ENV: prod
         PHX_HOST: my_app.minasmazar.org
         SECRET_KEY_BASE: 50Ek5r7GwQlQCJlFi5y+O5Mmq0z/qHMRirG7IEim7w1B7H0fxnegANr0bRe26bE3
         # MY_APP_SSL_KEY_PATH: /root/my_app/priv/ssl/my_app.minasmazar.org-key.pem
         # MY_APP_SSL_CERT_PATH: /root/my_app/priv/ssl/my_app.minasmazar.org.pem
         PORT: 80
      ports:
         # Mapping the port to make the Phoenix app accessible outside of the container.
         - '80:80'
         - '443:443'
      expose:
        - '80'
        - '443'
      depends_on:
         # The DB container needs to be started before we start this container.
         - db
      networks:
        - outside
        - default
   db:
      # We use the predefined Postgres image.
      image: postgres:9.6
      environment:
         # Set user/password for Postgres.
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         # Set a path where Postgres should store the data.
         PGDATA: /var/lib/postgresql/data/pgdata
      ports:
        - '5432:5432'
      expose:
        - '5432'
      restart: always
      volumes:
         - pgdata:/var/lib/postgresql/data
      networks:
        - default

# Define the volumes.
volumes:
   pgdata:

# Define networks
networks:
  outside:

#+end_src
** Mocking ([[https://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/][a blogpost from José Valim]])
** Scale serverless with [[https://fly.io/blog/rethinking-serverless-with-flame/][FLAME]]!
** [[https://shaolang.github.io/posts/2021-06-04-phoenix-pubsub-comms-across-nodes/][Phoenix Pubsub comms across nodes]]
** Phoenix Livebooks

- [[https://notes.club/][Discover Livebook notebooks (Elixir)]]
- https://github.com/aslakjohansen/livebook-demos
- https://github.com/Arp-G/async-elixir
- https://github.com/whatyouhide/guide_async_processing_in_elixir

** [[https://nerves-project.org/newsletter/][Nerves]]

- [[https://nerves-project.org/newsletter/][Nervers newsletter]]

* [[https://www.raspberrypi.com/tutorials/how-to-use-a-raspberry-pi-in-kiosk-mode/][How to use a Raspberry Pi in /kiosk mode/]]
* systemd and journalctl

Add a service to systemd

More info [[https://learn.sparkfun.com/tutorials/how-to-run-a-raspberry-pi-program-on-startup/all][here]]. Here's an article on how to create and manage [[https://www.baeldung.com/linux/systemd-create-user-services][user’s services With systemd]].

#+begin_src toml
# /lib/systemd/system/clock.service
  [Unit]
  Description=Start Clock

  [Service]
  Environment=DISPLAY=:0
  Environment=XAUTHORITY=/home/pi/.Xauthority
  ExecStart=/usr/bin/python3 /home/pi/clock.py
  Restart=always
  RestartSec=10s
  KillMode=process
  TimeoutSec=infinity

  [Install]
  WantedBy=graphical.target
#+end_src

Clear journalctl

The self maintenance method is to vacuum the logs by size or time. Retain only the past two days:

#+begin_src sh
journalctl --vacuum-time=2d
#+end_src

or retain only the past 500 MB

#+begin_src sh
journalctl --vacuum-size=500M
#+end_src

* MacOS
** Reset DNS cache on Macos

Taken from [[https://www.lifewire.com/flush-dns-cache-on-a-mac-5209298][this article]].

#+begin_src shell
  sudo dscacheutil -flushcache
  sudo killall -HUP mDNSResponder
#+end_src

** Let QuickPlayer to autoplay on open

Taken from this [[https://osxdaily.com/2009/09/03/autoplay-quicktime-movies-on-open-and-5-other-useful-quicktime-x-hacks/][Osx Daily post]]. ⚠️ /it seems not working on my Mac/ 🤔 

#+begin_src sh
defaults write com.apple.QuickTimePlayerX MGPlayMovieOnOpen 1
#+end_src

* Youtube downloader (yt-dlp)

Search for videos.

#+begin_src sh
  yt-dlp ytsearch10:lebron james --get-id --get-title
#+end_src

* FFMPEG
** Extract audio from video
#+begin_example shell
ffmpeg -i infile.mp4 -vn -acodec copy outfile.ogg
#+end_example

#+RESULTS:

** Cut audio/videos starting from 10s from the beginning for 20s.

#+BEGIN_EXAMPLE sh
ffmpeg -ss 10 -t 20 -i infile.wav outfule.wav
#+END_EXAMPLE

Another example using timing

#+begin_example
ffmpeg -ss 00:00:15.00 -i in.mp4 -t 00:00:10.00 -c copy out.mp4
#+end_example

** Adjust volume

If we want our volume to be half of the input volume:
#+BEGIN_EXAMPLE 
ffmpeg -i input.wav -filter:a "volume=0.5" output.wav
#+END_EXAMPLE

150% of current volume:
#+BEGIN_EXAMPLE 
ffmpeg -i input.wav -filter:a "volume=1.5" output.wav
#+END_EXAMPLE

You can also use decibel measures. To increase the volume by 10dB:
#+BEGIN_EXAMPLE 
ffmpeg -i input.wav -filter:a "volume=10dB" output.wav
#+END_EXAMPLE

** Speeding up/slowing down video:

The filter works by changing the presentation timestamp (PTS) of each
video frame. For example, if there are two succesive frames shown at
timestamps 1 and 2, and you want to speed up the video, those
timestamps need to become 0.5 and 1, respectively. Thus, we have to
multiply them by 0.5.

To double the speed of the video, you can use:
#+BEGIN_EXAMPLE sh
ffmpeg -i input.mkv -filter:v "setpts=0.5*PTS" output.mkv
#+END_EXAMPLE

To slow down your video, you have to use a multiplier greater than 1:
#+BEGIN_EXAMPLE sh
ffmpeg -i input.mkv -filter:v "setpts=2.0*PTS" output.mkv
#+END_EXAMPLE

For audio I found this

#+begin_src sh
ffmpeg -i input.wav -filter:a "atempo=0.75" output.mp3 
#+end_src
** Concat audio/videos starting from a list of files

#+BEGIN_EXAMPLE sh
ffmpeg -f concat -i list-of-files.txt -c copy outfile.wav
#+END_EXAMPLE

The ~list-of-files.txt~ should be something like this:

#+begin_example
file './infile.wav'
file './infile.wav'
file './infile.wav'
file './infile.wav'
file './infile.wav'
file './infile.wav'
#+end_example

**N.B.** you could see the error 'Unsafe filename..Operation not permitted'; as reported in [[https://stackoverflow.com/questions/38996925/ffmpeg-concat-unsafe-file-name][this SO thread]] you could solve this issue by using single quotes in the list of filenames, avoiding any ~~~ or other /"strange"/ chars.

** Extract single frame

Extract a single frame at time 10s (also consider using ~accurate_seek~ argument).

#+begin_example shell
ffmpeg -i vid.mp4 -ss 10 -frames:v 1 thumb.png
#+end_example

Extract a frame each minute.

#+begin_example shell
ffmpeg -i vid.mp4 -vf fps=1/60 thumb%03d.png
#+end_example

** Extract scenes

Extract scenes! You'll receive an output with some lines starting with ~Parsed_showinfo~.

#+begin_src sh
  ffmpeg -i source.mp4 -filter:v "select='gt(scene,0.4)',showinfo" -f null - 2>&1
#+end_src

** Change sample rate

Converts a.wav to MPEG audio at 22050 Hz sample rate.

#+begin_example sh
  ffmpeg -i /tmp/a.wav -ar 22050 /tmp/a.mp2
#+end_example
** Edit ID3 Tags

You can follow [[https://gist.github.com/eyecatchup/0757b3d8b989fe433979db2ea7d95a01][this gist]].
#+begin_example sh
  ffmpeg -i file.mp3 -metadata title="Track Title" -metadata artist="The artist" -metadata album="Album name" out.mp3
#+end_example
** Capture audio

Taken from [[https://trac.ffmpeg.org/wiki/Capture/Desktop][FFMPEG doc]]

**** Linux
Use the x11grab device:

#+begin_src sh
ffmpeg -video_size 1024x768 -framerate 25 -f x11grab -i :0.0+100,200 output.mp4
#+end_src
This will grab the image from desktop, starting with the upper-left corner at x=100, y=200 with a width and height of 1024⨉768.

If you need audio too, you can use ALSA (see Capture/ALSA for more info):

#+begin_src sh
ffmpeg -video_size 1024x768 -framerate 25 -f x11grab -i :0.0+100,200 -f alsa -ac 2 -i hw:0 output.mkv
#+end_src

Or the pulse input device (see Capture/PulseAudio for more info):

#+begin_src sh
ffmpeg -video_size 1024x768 -framerate 25 -f x11grab -i :0.0+100,200 -f pulse -ac 2 -i default output.mkv
#+end_src

***** macOS
Use the avfoundation device:

#+begin_src sh
ffmpeg -f avfoundation -list_devices true -i ""
#+end_src

#+RESULTS:

This will enumerate all the available input devices including screens ready to be captured.

Once you've figured out the device index corresponding to the screen to be captured, use:

#+begin_src sh
ffmpeg -f avfoundation -i "<screen device index>:<audio device index>" output.mkv
#+end_src

This will capture the screen from <screen device index> and audio from <audio device index> into the output file output.mkv.

To capture only audio, something like this:

#+begin_src sh
ffmpeg -f avfoundation -i ":default" output.wav
#+end_src

* Makefile

- https://makefiletutorial.com/

A sample of makefile usefull for /day-to-day/ development: fetch the remote repo (=sync=) avoiding to digit the ssh passowrd everytime (=sshadd=)

#+begin_src makefile
  sync:
          git fetch
          git pull origin master
  # I guess that happens in a custom session, so won't work
  #
  # sshadd:
  # 	eval `ssh-agent -s`
  # 	ssh-add
#+end_src

#+begin_src makefile
  default: docker-build docker-start

  docker-build:
  	docker build -t darbula:latest .
  docker-start:
  	docker container run --name darbula -p 4020:4020 --rm -t darbula:latest /app/bin/darbula start
#+end_src

Simple example on how to use =make= variables and shell environment variables.

#+begin_src makefile
  app := $$APP

  default: .elixir.phoenix.new.live

  .elixir.phoenix.new.live:
  	new ${app} --live
#+end_src

* Tailwind
** Background Colors
#+begin_src text
  Class  Properties  Preview     
  bg-inherit  background-color: inherit;       
  bg-current  background-color: currentColor;       
  bg-transparent  background-color: transparent;       
  bg-black  background-color: rgb(0 0 0);       
  bg-white  background-color: rgb(255 255 255);       
  bg-slate-50  background-color: rgb(248 250 252);       
  bg-slate-100  background-color: rgb(241 245 249);       
  bg-slate-200  background-color: rgb(226 232 240);       
  bg-slate-300  background-color: rgb(203 213 225);       
  bg-slate-400  background-color: rgb(148 163 184);       
  bg-slate-500  background-color: rgb(100 116 139);       
  bg-slate-600  background-color: rgb(71 85 105);       
  bg-slate-700  background-color: rgb(51 65 85);       
  bg-slate-800  background-color: rgb(30 41 59);       
  bg-slate-900  background-color: rgb(15 23 42);       
  bg-slate-950  background-color: rgb(2 6 23);       
  bg-gray-50  background-color: rgb(249 250 251);       
  bg-gray-100  background-color: rgb(243 244 246);       
  bg-gray-200  background-color: rgb(229 231 235);       
  bg-gray-300  background-color: rgb(209 213 219);       
  bg-gray-400  background-color: rgb(156 163 175);       
  bg-gray-500  background-color: rgb(107 114 128);       
  bg-gray-600  background-color: rgb(75 85 99);       
  bg-gray-700  background-color: rgb(55 65 81);       
  bg-gray-800  background-color: rgb(31 41 55);       
  bg-gray-900  background-color: rgb(17 24 39);       
  bg-gray-950  background-color: rgb(3 7 18);       
  bg-zinc-50  background-color: rgb(250 250 250);       
  bg-zinc-100  background-color: rgb(244 244 245);       
  bg-zinc-200  background-color: rgb(228 228 231);       
  bg-zinc-300  background-color: rgb(212 212 216);       
  bg-zinc-400  background-color: rgb(161 161 170);       
  bg-zinc-500  background-color: rgb(113 113 122);       
  bg-zinc-600  background-color: rgb(82 82 91);       
  bg-zinc-700  background-color: rgb(63 63 70);       
  bg-zinc-800  background-color: rgb(39 39 42);       
  bg-zinc-900  background-color: rgb(24 24 27);       
  bg-zinc-950  background-color: rgb(9 9 11);       
  bg-neutral-50  background-color: rgb(250 250 250);       
  bg-neutral-100  background-color: rgb(245 245 245);       
  bg-neutral-200  background-color: rgb(229 229 229);       
  bg-neutral-300  background-color: rgb(212 212 212);       
  bg-neutral-400  background-color: rgb(163 163 163);       
  bg-neutral-500  background-color: rgb(115 115 115);       
  bg-neutral-600  background-color: rgb(82 82 82);       
  bg-neutral-700  background-color: rgb(64 64 64);       
  bg-neutral-800  background-color: rgb(38 38 38);       
  bg-neutral-900  background-color: rgb(23 23 23);       
  bg-neutral-950  background-color: rgb(10 10 10);       
  bg-stone-50  background-color: rgb(250 250 249);       
  bg-stone-100  background-color: rgb(245 245 244);       
  bg-stone-200  background-color: rgb(231 229 228);       
  bg-stone-300  background-color: rgb(214 211 209);       
  bg-stone-400  background-color: rgb(168 162 158);       
  bg-stone-500  background-color: rgb(120 113 108);       
  bg-stone-600  background-color: rgb(87 83 78);       
  bg-stone-700  background-color: rgb(68 64 60);       
  bg-stone-800  background-color: rgb(41 37 36);       
  bg-stone-900  background-color: rgb(28 25 23);       
  bg-stone-950  background-color: rgb(12 10 9);       
  bg-red-50  background-color: rgb(254 242 242);       
  bg-red-100  background-color: rgb(254 226 226);       
  bg-red-200  background-color: rgb(254 202 202);       
  bg-red-300  background-color: rgb(252 165 165);       
  bg-red-400  background-color: rgb(248 113 113);       
  bg-red-500  background-color: rgb(239 68 68);       
  bg-red-600  background-color: rgb(220 38 38);       
  bg-red-700  background-color: rgb(185 28 28);       
  bg-red-800  background-color: rgb(153 27 27);       
  bg-red-900  background-color: rgb(127 29 29);       
  bg-red-950  background-color: rgb(69 10 10);       
  bg-orange-50  background-color: rgb(255 247 237);       
  bg-orange-100  background-color: rgb(255 237 213);       
  bg-orange-200  background-color: rgb(254 215 170);       
  bg-orange-300  background-color: rgb(253 186 116);       
  bg-orange-400  background-color: rgb(251 146 60);       
  bg-orange-500  background-color: rgb(249 115 22);       
  bg-orange-600  background-color: rgb(234 88 12);       
  bg-orange-700  background-color: rgb(194 65 12);       
  bg-orange-800  background-color: rgb(154 52 18);       
  bg-orange-900  background-color: rgb(124 45 18);       
  bg-orange-950  background-color: rgb(67 20 7);       
  bg-amber-50  background-color: rgb(255 251 235);       
  bg-amber-100  background-color: rgb(254 243 199);       
  bg-amber-200  background-color: rgb(253 230 138);       
  bg-amber-300  background-color: rgb(252 211 77);       
  bg-amber-400  background-color: rgb(251 191 36);       
  bg-amber-500  background-color: rgb(245 158 11);       
  bg-amber-600  background-color: rgb(217 119 6);       
  bg-amber-700  background-color: rgb(180 83 9);       
  bg-amber-800  background-color: rgb(146 64 14);       
  bg-amber-900  background-color: rgb(120 53 15);       
  bg-amber-950  background-color: rgb(69 26 3);       
  bg-yellow-50  background-color: rgb(254 252 232);       
  bg-yellow-100  background-color: rgb(254 249 195);       
  bg-yellow-200  background-color: rgb(254 240 138);       
  bg-yellow-300  background-color: rgb(253 224 71);       
  bg-yellow-400  background-color: rgb(250 204 21);       
  bg-yellow-500  background-color: rgb(234 179 8);       
  bg-yellow-600  background-color: rgb(202 138 4);       
  bg-yellow-700  background-color: rgb(161 98 7);       
  bg-yellow-800  background-color: rgb(133 77 14);       
  bg-yellow-900  background-color: rgb(113 63 18);       
  bg-yellow-950  background-color: rgb(66 32 6);       
  bg-lime-50  background-color: rgb(247 254 231);       
  bg-lime-100  background-color: rgb(236 252 203);       
  bg-lime-200  background-color: rgb(217 249 157);       
  bg-lime-300  background-color: rgb(190 242 100);       
  bg-lime-400  background-color: rgb(163 230 53);       
  bg-lime-500  background-color: rgb(132 204 22);       
  bg-lime-600  background-color: rgb(101 163 13);       
  bg-lime-700  background-color: rgb(77 124 15);       
  bg-lime-800  background-color: rgb(63 98 18);       
  bg-lime-900  background-color: rgb(54 83 20);       
  bg-lime-950  background-color: rgb(26 46 5);       
  bg-green-50  background-color: rgb(240 253 244);       
  bg-green-100  background-color: rgb(220 252 231);       
  bg-green-200  background-color: rgb(187 247 208);       
  bg-green-300  background-color: rgb(134 239 172);       
  bg-green-400  background-color: rgb(74 222 128);       
  bg-green-500  background-color: rgb(34 197 94);       
  bg-green-600  background-color: rgb(22 163 74);       
  bg-green-700  background-color: rgb(21 128 61);       
  bg-green-800  background-color: rgb(22 101 52);       
  bg-green-900  background-color: rgb(20 83 45);       
  bg-green-950  background-color: rgb(5 46 22);       
  bg-emerald-50  background-color: rgb(236 253 245);       
  bg-emerald-100  background-color: rgb(209 250 229);       
  bg-emerald-200  background-color: rgb(167 243 208);       
  bg-emerald-300  background-color: rgb(110 231 183);       
  bg-emerald-400  background-color: rgb(52 211 153);       
  bg-emerald-500  background-color: rgb(16 185 129);       
  bg-emerald-600  background-color: rgb(5 150 105);       
  bg-emerald-700  background-color: rgb(4 120 87);       
  bg-emerald-800  background-color: rgb(6 95 70);       
  bg-emerald-900  background-color: rgb(6 78 59);       
  bg-emerald-950  background-color: rgb(2 44 34);       
  bg-teal-50  background-color: rgb(240 253 250);       
  bg-teal-100  background-color: rgb(204 251 241);       
  bg-teal-200  background-color: rgb(153 246 228);       
  bg-teal-300  background-color: rgb(94 234 212);       
  bg-teal-400  background-color: rgb(45 212 191);       
  bg-teal-500  background-color: rgb(20 184 166);       
  bg-teal-600  background-color: rgb(13 148 136);       
  bg-teal-700  background-color: rgb(15 118 110);       
  bg-teal-800  background-color: rgb(17 94 89);       
  bg-teal-900  background-color: rgb(19 78 74);       
  bg-teal-950  background-color: rgb(4 47 46);       
  bg-cyan-50  background-color: rgb(236 254 255);       
  bg-cyan-100  background-color: rgb(207 250 254);       
  bg-cyan-200  background-color: rgb(165 243 252);       
  bg-cyan-300  background-color: rgb(103 232 249);       
  bg-cyan-400  background-color: rgb(34 211 238);       
  bg-cyan-500  background-color: rgb(6 182 212);       
  bg-cyan-600  background-color: rgb(8 145 178);       
  bg-cyan-700  background-color: rgb(14 116 144);       
  bg-cyan-800  background-color: rgb(21 94 117);       
  bg-cyan-900  background-color: rgb(22 78 99);       
  bg-cyan-950  background-color: rgb(8 51 68);       
  bg-sky-50  background-color: rgb(240 249 255);       
  bg-sky-100  background-color: rgb(224 242 254);       
  bg-sky-200  background-color: rgb(186 230 253);       
  bg-sky-300  background-color: rgb(125 211 252);       
  bg-sky-400  background-color: rgb(56 189 248);       
  bg-sky-500  background-color: rgb(14 165 233);       
  bg-sky-600  background-color: rgb(2 132 199);       
  bg-sky-700  background-color: rgb(3 105 161);       
  bg-sky-800  background-color: rgb(7 89 133);       
  bg-sky-900  background-color: rgb(12 74 110);       
  bg-sky-950  background-color: rgb(8 47 73);       
  bg-blue-50  background-color: rgb(239 246 255);       
  bg-blue-100  background-color: rgb(219 234 254);       
  bg-blue-200  background-color: rgb(191 219 254);       
  bg-blue-300  background-color: rgb(147 197 253);       
  bg-blue-400  background-color: rgb(96 165 250);       
  bg-blue-500  background-color: rgb(59 130 246);       
  bg-blue-600  background-color: rgb(37 99 235);       
  bg-blue-700  background-color: rgb(29 78 216);       
  bg-blue-800  background-color: rgb(30 64 175);       
  bg-blue-900  background-color: rgb(30 58 138);       
  bg-blue-950  background-color: rgb(23 37 84);       
  bg-indigo-50  background-color: rgb(238 242 255);       
  bg-indigo-100  background-color: rgb(224 231 255);       
  bg-indigo-200  background-color: rgb(199 210 254);       
  bg-indigo-300  background-color: rgb(165 180 252);       
  bg-indigo-400  background-color: rgb(129 140 248);       
  bg-indigo-500  background-color: rgb(99 102 241);       
  bg-indigo-600  background-color: rgb(79 70 229);       
  bg-indigo-700  background-color: rgb(67 56 202);       
  bg-indigo-800  background-color: rgb(55 48 163);       
  bg-indigo-900  background-color: rgb(49 46 129);       
  bg-indigo-950  background-color: rgb(30 27 75);       
  bg-violet-50  background-color: rgb(245 243 255);       
  bg-violet-100  background-color: rgb(237 233 254);       
  bg-violet-200  background-color: rgb(221 214 254);       
  bg-violet-300  background-color: rgb(196 181 253);       
  bg-violet-400  background-color: rgb(167 139 250);       
  bg-violet-500  background-color: rgb(139 92 246);       
  bg-violet-600  background-color: rgb(124 58 237);       
  bg-violet-700  background-color: rgb(109 40 217);       
  bg-violet-800  background-color: rgb(91 33 182);       
  bg-violet-900  background-color: rgb(76 29 149);       
  bg-violet-950  background-color: rgb(46 16 101);       
  bg-purple-50  background-color: rgb(250 245 255);       
  bg-purple-100  background-color: rgb(243 232 255);       
  bg-purple-200  background-color: rgb(233 213 255);       
  bg-purple-300  background-color: rgb(216 180 254);       
  bg-purple-400  background-color: rgb(192 132 252);       
  bg-purple-500  background-color: rgb(168 85 247);       
  bg-purple-600  background-color: rgb(147 51 234);       
  bg-purple-700  background-color: rgb(126 34 206);       
  bg-purple-800  background-color: rgb(107 33 168);       
  bg-purple-900  background-color: rgb(88 28 135);       
  bg-purple-950  background-color: rgb(59 7 100);       
  bg-fuchsia-50  background-color: rgb(253 244 255);       
  bg-fuchsia-100  background-color: rgb(250 232 255);       
  bg-fuchsia-200  background-color: rgb(245 208 254);       
  bg-fuchsia-300  background-color: rgb(240 171 252);       
  bg-fuchsia-400  background-color: rgb(232 121 249);       
  bg-fuchsia-500  background-color: rgb(217 70 239);       
  bg-fuchsia-600  background-color: rgb(192 38 211);       
  bg-fuchsia-700  background-color: rgb(162 28 175);       
  bg-fuchsia-800  background-color: rgb(134 25 143);       
  bg-fuchsia-900  background-color: rgb(112 26 117);       
  bg-fuchsia-950  background-color: rgb(74 4 78);       
  bg-pink-50  background-color: rgb(253 242 248);       
  bg-pink-100  background-color: rgb(252 231 243);       
  bg-pink-200  background-color: rgb(251 207 232);       
  bg-pink-300  background-color: rgb(249 168 212);       
  bg-pink-400  background-color: rgb(244 114 182);       
  bg-pink-500  background-color: rgb(236 72 153);       
  bg-pink-600  background-color: rgb(219 39 119);       
  bg-pink-700  background-color: rgb(190 24 93);       
  bg-pink-800  background-color: rgb(157 23 77);       
  bg-pink-900  background-color: rgb(131 24 67);       
  bg-pink-950  background-color: rgb(80 7 36);       
  bg-rose-50  background-color: rgb(255 241 242);       
  bg-rose-100  background-color: rgb(255 228 230);       
  bg-rose-200  background-color: rgb(254 205 211);       
  bg-rose-300  background-color: rgb(253 164 175);       
  bg-rose-400  background-color: rgb(251 113 133);       
  bg-rose-500  background-color: rgb(244 63 94);       
  bg-rose-600  background-color: rgb(225 29 72);       
  bg-rose-700  background-color: rgb(190 18 60);       
  bg-rose-800  background-color: rgb(159 18 57);       
  bg-rose-900  background-color: rgb(136 19 55);       
  bg-rose-950  background-color: rgb(76 5 25);       
#+end_src
* [[file:holymacs/ide.org::*Run make on list of projects][Run make on list of projects]]
* Google Chrome & chromedriver

Download chromedriver version according to the version of Google Chrome installed.
- https://googlechromelabs.github.io/chrome-for-testing/

How to get rid of "Choose your search engine" dialog in Chrome v.127 on Selenium test run?

#+begin_src sh
chromedriver --disable-search-engine-choice-screen
#+end_src

* GPG and SSH
** Generate key

Ref. https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key

Remember to execute in a terminal capable of reading password via ncurses-like input method.

  #+begin_src sh
gpg --full-generate-key
  #+end_src

** List the key

#+begin_src sh
gpg --list-secret-keys --keyid-format=long
#+end_src

** Get the armored key text

  #+begin_src sh
gpg --armor --export KEYID
  #+end_src

** Upload to Github

Ref. https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-new-gpg-key-to-your-github-account

From the list of GPG keys, copy the long form of the GPG key ID you'd like to use. In this example, the GPG key ID is =3AA5C34371567BD2=:

#+begin_src sh
$ gpg --list-secret-keys --keyid-format=long
#+end_src

This will output something like

#+begin_src
/Users/hubot/.gnupg/secring.gpg
------------------------------------
sec   4096R/3AA5C34371567BD2 2016-03-10 [expires: 2017-03-10]
uid                          Hubot
ssb   4096R/42B317FD4BA89E7A 2016-03-10
#+end_src

Paste the text below, substituting in the GPG key ID you'd like to use. In this example, the GPG key ID is =3AA5C34371567BD2=:

#+begin_src sh
$ gpg --armor --export 3AA5C34371567BD2
#+end_src

Copy your GPG key, beginning with -----BEGIN PGP PUBLIC KEY BLOCK----- and ending with -----END PGP PUBLIC KEY BLOCK-----.

** Tell Git to use GPG key

Ref. https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key

Use the =gpg --list-secret-keys --keyid-format=long= command to list the long form of the GPG keys for which you have both a public and private key. A private key is required for signing commits or tags (same ID as for /Upload to Github/). Then:

#+begin_src sh
git config --global user.signingkey 3AA5C34371567BD2
#+end_src

** Export key pair

Ref. https://unix.stackexchange.com/questions/481939/how-to-export-a-gpg-private-key-and-public-key-to-a-file

*** Export Public Key

This command will export an ascii armored version of the public key:

#+begin_src sh
gpg --output public.pgp --armor --export username@email
#+end_src

N.B. when using =--armor= maybe the file extension name should be =.asc=.

*** Export Secret Key

This command will export an ascii armored version of the secret key:

#+begin_src sh
gpg --output private.pgp --armor --export-secret-key username@email
#+end_src

N.B. when using =--armor= maybe the file extension name should be =.asc=.

Or [[https://unix.stackexchange.com/questions/481939/how-to-export-a-gpg-private-key-and-public-key-to-a-file][if the purpose is to create a backup key, you should use the backup option]]:

#+begin_src sh
  gpg --output backupkeys.pgp --armor --export-secret-keys --export-options export-backup user@email
#+end_src

*** Security Concerns, Backup, and Storage

A PGP public key contains information about one's email address. This is generally acceptable since the public key is used to encrypt email to your address. However, in some cases, this is undesirable.

For most use cases, the secret key need not be exported and should not be distributed. If the purpose is to create a backup key, you should use the backup option:

#+begin_src shell
gpg --output backupkeys.pgp --armor --export-secret-keys --export-options export-backup user@email
#+end_src

** Import a key

#+begin_src shell
gpg --import my-key.asc
gpg --import --allow-secret-key-import private.key
#+end_src

** Troubleshooting

Interesting resources if you encounter problems:
- https://gist.github.com/paolocarrasco/18ca8fe6e63490ae1be23e84a7039374

** Generate SSH keys

From [[https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent][GitHub docs]]:

#+begin_src sh
ssh-keygen -t ed25519 -C "your_email@example.com"
#+end_src

** GPG Agent: cache and timeouts
**** Keep GnuPG credentials cached for entire user session

For GnuPG 2.1 and below edit user configuration file at =~/.gnupg/gpg-agent.conf=. In the example below the TTL is set to 3h.

#+begin_src sh :tangle ~/.gnupg/gpg-agent.conf
default-cache-ttl 10800
max-cache-ttl 10800
#+end_src

Then restart the agent

#+begin_src sh
  gpgconf --kill gpg-agent
  gpg-agent --daemon --use-standard-socket
#+end_src

**** Cache SSH keys

If you want to use SSH but tired of insert SSH key on every (for instance) git operation

#+begin_src sh
eval `ssh-agent -s`
ssh-add
#+end_src

#+begin_quote
SSH needs two things in order to use ssh-agent: an ssh-agent instance
running in the background, and an environment variable set that tells
SSH which socket it should use to connect to the agent (SSH_AUTH_SOCK
IIRC). If you just run ssh-agent then the agent will start, but SSH
will have no idea where to find it.
#+end_quote

More info in this [[https://stackoverflow.com/questions/17846529/could-not-open-a-connection-to-your-authentication-agent][SO thread]].
